#!/usr/bin/env python3
"""Extract reproducible, repository-derived facts for the KM paper."""

from __future__ import annotations

import collections
import csv
import pathlib
import re
import subprocess


ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "generated"
TAG = "v1.3.0"


def git(*args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(ROOT), *args], text=True
    ).strip()


def count_tree_lines(prefix: str, suffix: str) -> tuple[int, int]:
    """Count source files and lines in the exact release tree, not the checkout."""
    files = [path for path in git("ls-tree", "-r", "--name-only", TAG, "--", prefix).splitlines()
             if path.endswith(suffix)]
    return len(files), sum(len(git("show", f"{TAG}:{path}").splitlines()) for path in files)


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in value)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    raw = git(
        "log",
        "--reverse",
        "--date=iso-strict",
        "--pretty=%H%x09%ad%x09%an%x09%s%x09%B%x1e",
        TAG,
    )
    trailer_counts: collections.Counter[str] = collections.Counter()
    day_counts: collections.Counter[str] = collections.Counter()
    for record in raw.split("\x1e"):
        record = record.strip()
        if not record:
            continue
        first, *body_lines = record.splitlines()
        commit, date, author, subject, first_body = first.split("\t", 4)
        body = "\n".join([first_body, *body_lines])
        day = date[:10]
        day_counts[day] += 1
        for match in re.finditer(r"(?im)^Co-Authored-By:\s*(.+)$", body):
            trailer_counts[match.group(1).strip()] += 1
        rows.append((commit, date, author, subject))

    with (OUT / "commit-timeline.tsv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t", lineterminator="\n")
        writer.writerow(["commit", "date", "author", "subject"])
        writer.writerows(rows)

    with (OUT / "commits-by-day.tsv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t", lineterminator="\n")
        writer.writerow(["date", "commits"])
        writer.writerows(sorted(day_counts.items()))

    with (OUT / "model-trailers.tsv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t", lineterminator="\n")
        writer.writerow(["trailer_identity", "commits"])
        writer.writerows(trailer_counts.most_common())

    rust_files, rust_lines = count_tree_lines("engine/src", ".rs")
    lean_files, lean_lines = count_tree_lines("lean", ".lean")
    java_files, java_lines = count_tree_lines("protege/src", ".java")
    first_commit = rows[0]
    last_commit = rows[-1]
    trailer_total = sum(trailer_counts.values())
    commits_with_trailers = int(
        git("log", TAG, "--format=%H%x09%B%x1e").count("Co-Authored-By:") > 0
    )
    # Count commits, rather than trailers, with at least one model attribution.
    attributed_commits = 0
    for record in git("log", TAG, "--format=%B%x1e").split("\x1e"):
        if re.search(r"(?im)^Co-Authored-By:", record):
            attributed_commits += 1
    del commits_with_trailers

    summary = rf"""% Generated by paper/scripts/extract_history.py. Do not edit.
\newcommand{{\KMCommitCount}}{{{len(rows):,}}}
\newcommand{{\KMFirstDate}}{{{first_commit[1][:10]}}}
\newcommand{{\KMLastDate}}{{{last_commit[1][:10]}}}
\newcommand{{\KMFirstCommit}}{{\texttt{{{first_commit[0][:8]}}}}}
\newcommand{{\KMLastCommit}}{{\texttt{{{last_commit[0][:8]}}}}}
\newcommand{{\KMAttributedCommitCount}}{{{attributed_commits:,}}}
\newcommand{{\KMTrailerCount}}{{{trailer_total:,}}}
\newcommand{{\KMRustFiles}}{{{rust_files:,}}}
\newcommand{{\KMRustLines}}{{{rust_lines:,}}}
\newcommand{{\KMLeanFiles}}{{{lean_files:,}}}
\newcommand{{\KMLeanLines}}{{{lean_lines:,}}}
\newcommand{{\KMJavaFiles}}{{{java_files:,}}}
\newcommand{{\KMJavaLines}}{{{java_lines:,}}}
"""
    (OUT / "history-summary.tex").write_text(summary, encoding="utf-8")

    phases = [
        ("1", "2026-06-02", "2026-06-11", "Context engine and first audits"),
        ("2", "2026-06-12", "2026-07-29", "Hybridisation and corpus debugging"),
        ("3", "2026-07-30", "2026-08-16", "Automatic-route closure and optimisation"),
        ("4", "2026-08-17", "2026-08-24", "Integrated Lean certification"),
        ("5", "2026-08-25", "2026-08-30", "Release hardening and v1.3 interfaces"),
    ]
    phase_lines = [
        "% Generated by paper/scripts/extract_history.py. Do not edit.",
        r"\begin{tabular}{cllrr}",
        r"\toprule",
        r"Phase & Dates & Primary activity & Commits & Agent-attributed \\",
        r"\midrule",
    ]
    phase_tsv = []
    for number, start, end, label in phases:
        selected = [row for row in rows if start <= row[1][:10] <= end]
        attributed = 0
        for commit, _date, _author, _subject in selected:
            body = git("show", "-s", "--format=%B", commit)
            if re.search(r"(?im)^Co-Authored-By:", body):
                attributed += 1
        phase_tsv.append((number, start, end, label, len(selected), attributed))
        phase_lines.append(
            f"{number} & {start[5:]}--{end[5:]} & {tex_escape(label)} & "
            f"{len(selected):,} & {attributed:,} \\\\"
        )
    phase_lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    (OUT / "phase-stats.tex").write_text("\n".join(phase_lines), encoding="utf-8")
    with (OUT / "phase-stats.tsv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t", lineterminator="\n")
        writer.writerow(
            ["phase", "start", "end", "primary_activity", "commits", "agent_attributed"]
        )
        writer.writerows(phase_tsv)


if __name__ == "__main__":
    main()
