#!/usr/bin/env python3
"""Extract privacy-preserving evidence from retained KM Claude sessions.

The generated ledger records hashes and methodological category flags, not
conversation text.  It therefore supports process claims without publishing
private prompts or responses.
"""

from __future__ import annotations

import csv
import hashlib
import json
import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = pathlib.Path(
    "/home/leechuck/.claude/projects/"
    "-home-leechuck-Public-software-kobayashi-marust"
)
OUT = ROOT / "paper" / "generated"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def text_content(message: object) -> str:
    if not isinstance(message, dict):
        return str(message)
    content = message.get("content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            str(item.get("text", "")) if isinstance(item, dict) else str(item)
            for item in content
        )
    return str(content)


def flag(pattern: str, value: str) -> bool:
    return re.search(pattern, value, flags=re.IGNORECASE) is not None


def main() -> None:
    source = DEFAULT_SOURCE
    if not source.is_dir():
        raise SystemExit(f"retained KM session directory is absent: {source}")
    OUT.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, object]] = []
    for path in sorted(source.glob("*.jsonl")):
        raw = path.read_bytes()
        title = ""
        agent_name = ""
        first_user: dict[str, object] | None = None
        first_prompt = ""
        for line in raw.splitlines():
            try:
                event = json.loads(line)
            except (UnicodeDecodeError, json.JSONDecodeError):
                continue
            if event.get("type") == "custom-title":
                title = str(event.get("customTitle", ""))
            elif event.get("type") == "agent-name":
                agent_name = str(event.get("agentName", ""))
            elif event.get("type") == "user" and first_user is None:
                first_user = event
                first_prompt = text_content(event.get("message"))
        if first_user is None:
            continue
        normalized = " ".join(first_prompt.split())
        rows.append({
            "session_id": path.stem,
            "first_timestamp_utc": str(first_user.get("timestamp", "")),
            "source_sha256": digest(raw),
            "first_prompt_sha256": digest(normalized.encode()),
            "git_branch": str(first_user.get("gitBranch", "")),
            "cwd_sha256": digest(str(first_user.get("cwd", "")).encode()),
            "named_task": str(bool(title or agent_name)).lower(),
            "explicit_isolation": str(flag(r"isolated|work only in|work only on|worktree", normalized)).lower(),
            "read_only_review": str(flag(r"read[- ]only|review only|do not edit", normalized)).lower(),
            "implementation_task": str(flag(r"implement|make concrete progress|goal: make", normalized)).lower(),
            "lean_or_proof_task": str(flag(r"\blean\b|proof|certif", normalized)).lower(),
            "benchmark_or_performance_task": str(flag(r"benchmark|performance|wall[- ]time|memory|ontology|\bORE\b", normalized)).lower(),
        })

    fields = list(rows[0]) if rows else []
    with (OUT / "agent-session-evidence.tsv").open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, delimiter="\t", lineterminator="\n", fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    counts = {
        key: sum(row[key] == "true" for row in rows)
        for key in (
            "named_task", "explicit_isolation", "read_only_review",
            "implementation_task", "lean_or_proof_task",
            "benchmark_or_performance_task",
        )
    }
    tex = f"""% Generated by paper/scripts/extract_agent_sessions.py. Do not edit.
\\newcommand{{\\KMSessionEvidenceCount}}{{{len(rows)}}}
\\newcommand{{\\KMNamedAgentTaskCount}}{{{counts['named_task']}}}
\\newcommand{{\\KMIsolatedTaskEvidenceCount}}{{{counts['explicit_isolation']}}}
\\newcommand{{\\KMReadOnlyReviewEvidenceCount}}{{{counts['read_only_review']}}}
\\newcommand{{\\KMImplementationTaskEvidenceCount}}{{{counts['implementation_task']}}}
\\newcommand{{\\KMLeanTaskEvidenceCount}}{{{counts['lean_or_proof_task']}}}
\\newcommand{{\\KMBenchmarkTaskEvidenceCount}}{{{counts['benchmark_or_performance_task']}}}
"""
    (OUT / "agent-session-summary.tex").write_text(tex, encoding="utf-8")
    print(f"AGENT_SESSION_EVIDENCE_OK\t{len(rows)}\t{digest((OUT / 'agent-session-evidence.tsv').read_bytes())}")


if __name__ == "__main__":
    main()
