#!/usr/bin/env python3
"""Verify and atomically import seven hash-bound independent Fable reviews."""

from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path
import re
import shutil


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
ASPECTS = {
    1: ("Overall structure", "structure.md"),
    2: ("Section and paragraph flow", "flow.md"),
    3: ("Clarity", "clarity.md"),
    4: ("Writing style", "style.md"),
    5: ("Acronyms, notation, and technical terms", "terms.md"),
    6: ("Related work and state of the art", "related-work.md"),
    7: ("Citation support and bibliographic accuracy", "citations.md"),
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def locate(source: Path, number: int, suffix: str) -> Path:
    matches = sorted(source.glob(f"{number:02d}-*.{suffix}"))
    if len(matches) != 1:
        raise ValueError(f"expected one review {number} .{suffix}, found {len(matches)}")
    return matches[0]


def verify(source: Path, manuscript: Path) -> list[dict[str, str]]:
    manifest_path = source / "manifest.tsv"
    with manifest_path.open(encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream, delimiter="\t"))
    required = {"review", "aspect", "model", "manuscript_sha256", "seconds",
                "input_tokens", "output_tokens", "cache_creation_tokens",
                "cache_read_tokens", "raw_sha256", "report_sha256", "status"}
    if not rows or set(rows[0]) != required or len(rows) != 7:
        raise ValueError("review manifest does not contain the exact seven-row schema")
    manuscript_sha256 = digest(manuscript)
    seen = set()
    for row in rows:
        try:
            number = int(row["review"])
        except ValueError as error:
            raise ValueError("non-numeric review index") from error
        if number in seen or number not in ASPECTS:
            raise ValueError(f"duplicate or unknown review index: {number}")
        seen.add(number)
        title, _ = ASPECTS[number]
        if row["aspect"] != title or row["status"] != "complete":
            raise ValueError(f"review aspect/status mismatch: {number}")
        if row["model"] not in {"fable", "claude-fable-5"}:
            raise ValueError(f"review was not produced by Fable: {number}")
        if row["manuscript_sha256"] != manuscript_sha256:
            raise ValueError(f"review targets another manuscript: {number}")
        for field in ("input_tokens", "output_tokens", "cache_creation_tokens",
                      "cache_read_tokens"):
            if not row[field].isdigit() or int(row[field]) < 0:
                raise ValueError(f"invalid review usage counter {field}: {number}")
        if int(row["output_tokens"]) <= 0:
            raise ValueError(f"review has no output-token evidence: {number}")
        raw = locate(source, number, "json")
        report = locate(source, number, "md")
        if digest(raw) != row["raw_sha256"] or digest(report) != row["report_sha256"]:
            raise ValueError(f"review digest mismatch: {number}")
        text = report.read_text(encoding="utf-8")
        expected = (f"# Review {number}: {title}", manuscript_sha256,
                    "## Major findings", "## Minor findings", "## Verdict")
        if any(value not in text for value in expected):
            raise ValueError(f"review report schema mismatch: {number}")
    if seen != set(ASPECTS):
        raise ValueError("review index set is incomplete")
    return sorted(rows, key=lambda row: int(row["review"]))


def import_reviews(source: Path, manuscript: Path, target: Path) -> list[dict[str, str]]:
    rows = verify(source, manuscript)
    if target.exists():
        raise ValueError(f"refusing to overwrite imported reviews: {target}")
    temporary = target.with_name(target.name + ".part")
    if temporary.exists():
        shutil.rmtree(temporary)
    temporary.mkdir(parents=True)
    manuscript_sha256 = digest(manuscript)
    for row in rows:
        number = int(row["review"])
        _, destination = ASPECTS[number]
        shutil.copyfile(locate(source, number, "md"), temporary / destination)
    shutil.copyfile(source / "manifest.tsv", temporary / "review-usage.tsv")
    (temporary / "README.md").write_text(
        "# Independent paper reviews\n\n"
        f"All seven reports review `paper/main.tex` at SHA-256 `{manuscript_sha256}`.\n"
        "Raw Claude JSON receipts remain in the private build artifact; this directory\n"
        "contains the reports and native usage manifest. Author dispositions must be\n"
        "written separately and are not generated by the import process.\n",
        encoding="utf-8")
    temporary.replace(target)
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--manuscript", type=Path, default=PAPER / "main.tex")
    parser.add_argument("--target", type=Path, default=PAPER / "reviews")
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()
    rows = verify(args.source, args.manuscript) if args.verify_only else import_reviews(
        args.source, args.manuscript, args.target)
    print(f"FABLE_REVIEW_IMPORT_OK\t{len(rows)}\t{digest(args.manuscript)}")


if __name__ == "__main__":
    main()
