#!/usr/bin/env python3
"""Render the pinned, project-filtered AgentsView reports for the paper."""

from __future__ import annotations

import hashlib
import json
from datetime import date, timedelta
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "generated" / "agentsview"
EXPECTED = {
    "usage-daily-all.json": "9c92469fb4dd51d9e2e57dcb86af779c2cf529d569f264c36b3b4c48630c2f40",
    "stats-km-20260602-20260831.json": "764658cc9b1ccc1a081a562043480e25c3b241690a148565a9dcf3c2a87d89c4",
    "activity-km-20260602-20260831.json": "f9e53ddef80ab35549295519e7b12b4fba4774d598732a2f7aee5b476f497333",
    "version.txt": "74d98ebbce4428b0a8420435185aedb9cced4fb33bb85c6530e4dc3e560e962f",
}


def load(name: str) -> dict:
    path = EVIDENCE / name
    raw = path.read_bytes()
    actual = hashlib.sha256(raw).hexdigest()
    if actual != EXPECTED[name]:
        raise SystemExit(f"hash mismatch for {name}: {actual}")
    return json.loads(raw)


def grouped(rows: list[dict], key: str) -> dict[str, dict[str, int]]:
    result: dict[str, dict[str, int]] = {}
    for row in rows:
        for item in row[key]:
            target = result.setdefault(item["agent"], {
                "input": 0, "output": 0, "cache_create": 0, "cache_read": 0,
            })
            target["input"] += item["inputTokens"]
            target["output"] += item["outputTokens"]
            target["cache_create"] += item["cacheCreationTokens"]
            target["cache_read"] += item["cacheReadTokens"]
    return result


def integer(value: int) -> str:
    return f"{value:,}"


def decimal(value: float, digits: int = 1) -> str:
    return f"{value:,.{digits}f}"


PHASES = (
    ("Phase 2 (observed tail)", date(2026, 7, 11), date(2026, 7, 30)),
    ("Phase 3", date(2026, 7, 30), date(2026, 8, 17)),
    ("Phase 4", date(2026, 8, 17), date(2026, 8, 25)),
    ("Phase 5", date(2026, 8, 25), date(2026, 8, 31)),
)


def main() -> None:
    usage = load("usage-daily-all.json")
    stats = load("stats-km-20260602-20260831.json")
    activity = load("activity-km-20260602-20260831.json")
    version_path = EVIDENCE / "version.txt"
    if hashlib.sha256(version_path.read_bytes()).hexdigest() != EXPECTED["version.txt"]:
        raise SystemExit("hash mismatch for version.txt")

    agents = grouped(usage["daily"], "agentBreakdowns")
    models: dict[str, int] = {}
    for day in usage["daily"]:
        for row in day["modelBreakdowns"]:
            models[row["modelName"]] = models.get(row["modelName"], 0) + row["outputTokens"]
    sessions = stats["agent_portfolio"]["by_sessions"]
    minutes = {row["key"]: row["agent_minutes"] for row in activity["by_agent"]}
    observed = [row["date"] for row in usage["daily"] if row["outputTokens"]]
    totals = stats["totals"]
    tool_categories = stats["tool_mix"]["by_category"]
    assert sum(tool_categories.values()) == stats["tool_mix"]["total_calls"]

    # AgentsView's usage/activity reports agree on native API output-token
    # counters.  The stats model_mix field is a separate message-content token
    # measure, so it is intentionally not combined with these counters.
    assert usage["totals"]["outputTokens"] == activity["totals"]["output_tokens"]
    assert sum(row["output"] for row in agents.values()) == usage["totals"]["outputTokens"]

    usage_by_date = {date.fromisoformat(row["date"]): row for row in usage["daily"]}
    activity_by_date = {
        date.fromisoformat(row["start"][:10]): row for row in activity["buckets"]
    }
    phase_rows = []
    for label, start, end in PHASES:
        use = [row for day, row in usage_by_date.items() if start <= day < end]
        act = [row for day, row in activity_by_date.items() if start <= day < end]
        phase_rows.append({
            "label": label,
            "start": start,
            "end": end,
            "active_days": sum(row["outputTokens"] > 0 for row in use),
            "output": sum(row["outputTokens"] for row in use),
            "minutes": sum(row["agent_minutes"] for row in act),
            "peak": max((row["max_agents"] for row in act), default=0),
        })
    assert sum(row["output"] for row in phase_rows) == usage["totals"]["outputTokens"]
    assert abs(sum(row["minutes"] for row in phase_rows)
               - activity["totals"]["agent_minutes"]) < 0.01

    lines = [
        "% Generated by paper/scripts/render_agentsview_usage.py. Do not edit.",
        rf"\newcommand{{\KMAgentsViewVersion}}{{0.41.1}}",
        rf"\newcommand{{\KMAgentsViewFirstDate}}{{{min(observed)}}}",
        rf"\newcommand{{\KMAgentsViewLastDate}}{{{max(observed)}}}",
        rf"\newcommand{{\KMAgentsViewSessions}}{{{integer(totals['sessions_all'])}}}",
        rf"\newcommand{{\KMAgentsViewHumanSessions}}{{{integer(totals['sessions_human'])}}}",
        rf"\newcommand{{\KMAgentsViewSubagents}}{{{integer(totals['sessions_subagent'])}}}",
        rf"\newcommand{{\KMAgentsViewToolEvents}}{{{integer(stats['tool_mix']['total_calls'])}}}",
        rf"\newcommand{{\KMAgentsViewBashEvents}}{{{integer(tool_categories['Bash'])}}}",
        rf"\newcommand{{\KMAgentsViewEditEvents}}{{{integer(tool_categories['Edit'])}}}",
        rf"\newcommand{{\KMAgentsViewReadEvents}}{{{integer(tool_categories['Read'])}}}",
        rf"\newcommand{{\KMAgentsViewTaskEvents}}{{{integer(tool_categories['Task'])}}}",
        rf"\newcommand{{\KMAgentsViewWriteEvents}}{{{integer(tool_categories['Write'])}}}",
        rf"\newcommand{{\KMAgentsViewOtherEvents}}{{{integer(tool_categories['Other'])}}}",
        rf"\newcommand{{\KMAgentsViewPeak}}{{{integer(activity['peak']['agents'])}}}",
        rf"\newcommand{{\KMAgentsViewAgentMinutes}}{{{decimal(activity['totals']['agent_minutes'])}}}",
        rf"\newcommand{{\KMAgentsViewOutputTokens}}{{{integer(usage['totals']['outputTokens'])}}}",
        rf"\newcommand{{\KMPhaseThreeOutputShare}}{{{decimal(100 * phase_rows[1]['output'] / usage['totals']['outputTokens'])}\%}}",
        rf"\newcommand{{\KMPhaseThreeMinuteShare}}{{{decimal(100 * phase_rows[1]['minutes'] / activity['totals']['agent_minutes'])}\%}}",
        rf"\newcommand{{\KMPhaseFourOutputShare}}{{{decimal(100 * phase_rows[2]['output'] / usage['totals']['outputTokens'])}\%}}",
        rf"\newcommand{{\KMPhaseFourMinuteShare}}{{{decimal(100 * phase_rows[2]['minutes'] / activity['totals']['agent_minutes'])}\%}}",
        rf"\newcommand{{\KMFableOutput}}{{{integer(models['claude-fable-5'])}}}",
        rf"\newcommand{{\KMOpusFourOutput}}{{{integer(models['claude-opus-4-8'])}}}",
        rf"\newcommand{{\KMOpusFiveOutput}}{{{integer(models['claude-opus-5'])}}}",
        rf"\newcommand{{\KMCodexModelOutput}}{{{integer(models['gpt-5.6-sol'])}}}",
    ]
    for key, label in (("claude", "Claude"), ("codex", "Codex")):
        row = agents[key]
        lines.extend([
            rf"\newcommand{{\KM{label}NativeSessions}}{{{integer(sessions[key])}}}",
            rf"\newcommand{{\KM{label}NativeInput}}{{{integer(row['input'])}}}",
            rf"\newcommand{{\KM{label}NativeOutput}}{{{integer(row['output'])}}}",
            rf"\newcommand{{\KM{label}NativeCacheRead}}{{{integer(row['cache_read'])}}}",
            rf"\newcommand{{\KM{label}NativeCacheCreate}}{{{integer(row['cache_create'])}}}",
            rf"\newcommand{{\KM{label}AgentMinutes}}{{{decimal(minutes[key])}}}",
        ])
    (ROOT / "generated" / "agent-usage-summary.tex").write_text("\n".join(lines) + "\n")

    phase_lines = [
        "% Generated by paper/scripts/render_agentsview_usage.py. Do not edit.",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Phase & UTC interval & Active days & Output tokens & Agent-minutes & Peak \\",
        r"\midrule",
    ]
    for row in phase_rows:
        last = row["end"] - timedelta(days=1)
        interval = f"{row['start'].strftime('%d %b')}--{last.strftime('%d %b')}"
        phase_lines.append(
            f"{row['label']} & {interval} & {row['active_days']} & "
            f"{integer(row['output'])} & {decimal(row['minutes'])} & {row['peak']} \\\\"
        )
    phase_lines.extend([r"\bottomrule", r"\end{tabular}"])
    (ROOT / "generated" / "agent-usage-phases.tex").write_text(
        "\n".join(phase_lines) + "\n"
    )
    print(f"AGENTSVIEW_USAGE_OK\t{usage['totals']['outputTokens']}\t{totals['sessions_all']}")


if __name__ == "__main__":
    main()
