#!/usr/bin/env python3
"""Verify and render the selected KM development milestones."""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "paper" / "method-milestones.tsv"
OUTPUT = ROOT / "paper" / "generated" / "method-milestones.tex"


def git(*arguments: str) -> str:
    return subprocess.check_output(["git", *arguments], cwd=ROOT, text=True).rstrip("\n")


def main() -> None:
    with LEDGER.open(encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream, delimiter="\t"))
    if [int(row["order"]) for row in rows] != list(range(1, len(rows) + 1)):
        raise SystemExit("milestone order must be contiguous and start at one")

    previous_timestamp = ""
    seen: set[str] = set()
    for row in rows:
        commit = row["commit"]
        if commit in seen:
            raise SystemExit(f"duplicate milestone commit: {commit}")
        seen.add(commit)
        actual = git("show", "-s", "--format=%H%x09%cs%x09%aI", commit).split("\t")
        if actual[0] != commit or actual[1] != row["date"]:
            raise SystemExit(f"milestone provenance mismatch: {row!r} != {actual!r}")
        if previous_timestamp and actual[2] < previous_timestamp:
            raise SystemExit(f"milestones are not chronological at {commit}")
        previous_timestamp = actual[2]
        if subprocess.run(["git", "merge-base", "--is-ancestor", commit, "v1.3.0^{}"],
                          cwd=ROOT, check=False).returncode != 0:
            raise SystemExit(f"milestone is outside v1.3.0 history: {commit}")

    lines = [
        "% Generated by paper/scripts/render_method_milestones.py. Do not edit.",
        r"\begin{tabularx}{\textwidth}{rllX}",
        r"\toprule",
        r"Phase & Date & Commit & Verified milestone \\",
        r"\midrule",
    ]
    for row in rows:
        day = date.fromisoformat(row["date"])
        lines.append(
            f"{row['phase']} & {day.strftime('%d %b')} & "
            rf"\texttt{{{row['commit'][:8]}}} & {row['milestone']} \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabularx}"])
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"METHOD_MILESTONES_OK\t{len(rows)}")


if __name__ == "__main__":
    main()
