import ContextCalculus.CBFiniteLiteralOrderWire
import ContextCalculus.CBFiniteModel
import ContextCalculus.CBPredEnumeration

/-!
# Finite Hyper closure for production CB contexts

The production Hyper rule is indexed aggressively, but completeness must not
depend on an implementation posting list.  This module supplies the finite,
index-independent kernel used by the terminal checker:

* every substitution of a source clause over the checked term universe is
  enumerated;
* every provider is recomputed from the retained clauses and the checked
  literal order; and
* a sequence of checked providers is resolved against the instantiated source
  clause, with a semantic theorem for the complete sequence.

Later wire code only has to require retained strengthening of every normalized
candidate generated by these definitions.
-/

namespace ContextCalculus.CBHyperClosure

open ContextCalculus ContextCalculus.CheckerTerm
open ContextCalculus.CBFiniteModel
open ContextCalculus.CBFiniteLiteralOrderWire
open ContextCalculus.CBPredEnumeration
open ContextCalculus.CBProductionTrace
open ContextCalculus.CBLocalFactorClosureWire

/-! ## Exhaustive finite substitutions -/

/-- Turn one finite choice function into the corresponding simultaneous
substitution.  Variables retain the duplicate-free order from `varsC`. -/
def substitutionOf (terms : List FTerm) (vars : List Int)
    (values : Fin vars.length → Fin terms.length) :
    List (Int × FTerm) :=
  List.ofFn fun index => (vars.get index, terms.get (values index))

/-- All substitutions of every variable occurring in a clause by a term in
the checked finite universe. -/
def substitutions (terms : List FTerm) (clause : FCL) :
    List (List (Int × FTerm)) :=
  (allValues terms.length (varsC clause).length).map
    (substitutionOf terms (varsC clause))

theorem substitutionOf_mem_substitutions (terms : List FTerm) (clause : FCL)
    (values : Fin (varsC clause).length → Fin terms.length) :
    substitutionOf terms (varsC clause) values ∈ substitutions terms clause := by
  simp only [substitutions, List.mem_map]
  exact ⟨values, mem_allValues _ _ values, rfl⟩

theorem substitutionOf_length (terms : List FTerm) (vars : List Int)
    (values : Fin vars.length → Fin terms.length) :
    (substitutionOf terms vars values).length = vars.length := by
  simp [substitutionOf]

theorem substitutionOf_variables (terms : List FTerm) (vars : List Int)
    (values : Fin vars.length → Fin terms.length) :
    (substitutionOf terms vars values).map Prod.fst = vars := by
  unfold substitutionOf
  rw [← List.ofFn_comp']
  simpa using List.ofFn_get vars

theorem substitutionOf_terms_mem (terms : List FTerm) (vars : List Int)
    (values : Fin vars.length → Fin terms.length) :
    ∀ entry ∈ substitutionOf terms vars values, entry.2 ∈ terms := by
  intro entry hentry
  simp only [substitutionOf, List.mem_ofFn] at hentry
  obtain ⟨index, rfl⟩ := hentry
  exact List.get_mem terms (values index)

/-! ## Checked sequential Hyper resolution -/

/-- Resolve one provider for each selected body literal.  Every membership is
checked again, so malformed selections do not produce a candidate. -/
def resolveProviders : FCL → List (FLit × FCL) → Option FCL
  | clause, [] => some clause
  | clause, (literal, provider) :: providers =>
      if literal ∈ clause.body then
        if literal ∈ provider.head then
          resolveProviders (resolvent provider clause literal) providers
        else none
      else
        -- A prior resolution may have removed every duplicate occurrence of
        -- this instantiated body literal. It is already discharged.
        resolveProviders clause providers

theorem resolveProviders_sound {D : Type} (model : TModel D)
    (assignment : Int → D) :
    ∀ {source providers conclusion},
      resolveProviders source providers = some conclusion →
      HoldsAt model assignment source →
      (∀ selected ∈ providers, HoldsAt model assignment selected.2) →
      HoldsAt model assignment conclusion := by
  intro source providers
  induction providers generalizing source with
  | nil =>
      intro conclusion hresolve hsource _
      simp [resolveProviders] at hresolve
      subst conclusion
      exact hsource
  | cons selected providers ih =>
      rcases selected with ⟨literal, provider⟩
      intro conclusion hresolve hsource hproviders
      by_cases hbody : literal ∈ source.body
      · by_cases hhead : literal ∈ provider.head
        · simp only [resolveProviders, hbody, hhead] at hresolve
          apply ih hresolve
          · exact resolution_sound (model.evalL assignment) provider source literal
              (hproviders (literal, provider) (by simp)) hsource hhead hbody
          · intro selected hselected
            exact hproviders selected (by simp [hselected])
        · simp [resolveProviders, hbody, hhead] at hresolve
      · simp only [resolveProviders, hbody] at hresolve
        apply ih hresolve hsource
        intro selected hselected
        exact hproviders selected (by simp [hselected])

theorem resolveProviders_exists_of_provider_heads
    (source : FCL) (providers : List (FLit × FCL))
    (hheads : ∀ selected ∈ providers,
      selected.1 ∈ selected.2.head) :
    ∃ conclusion,
      resolveProviders source providers = some conclusion := by
  induction providers generalizing source with
  | nil => exact ⟨source, rfl⟩
  | cons selected providers ih =>
      rcases selected with ⟨literal, provider⟩
      have hhead : literal ∈ provider.head :=
        hheads (literal, provider) (by simp)
      have htail : ∀ selected ∈ providers,
          selected.1 ∈ selected.2.head := by
        intro selected hselected
        exact hheads selected (by simp [hselected])
      by_cases hbody : literal ∈ source.body
      · obtain ⟨conclusion, hconclusion⟩ :=
          ih (resolvent provider source literal) htail
        exact ⟨conclusion, by simp [resolveProviders, hbody, hhead,
          hconclusion]⟩
      · obtain ⟨conclusion, hconclusion⟩ := ih source htail
        exact ⟨conclusion, by simp [resolveProviders, hbody, hconclusion]⟩

def FalseAt (valuation : FLit → Prop) (clause : FCL) : Prop :=
  (∀ literal ∈ clause.body, valuation literal) ∧
    (∀ literal ∈ clause.head, ¬ valuation literal)

structure ProductiveAt (valuation : FLit → Prop) (clause : FCL)
    (selected : FLit) : Prop where
  selected_mem : selected ∈ clause.head
  body_true : ∀ literal ∈ clause.body, valuation literal
  other_false : ∀ literal ∈ clause.head,
    literal ≠ selected → ¬ valuation literal

theorem FalseAt.resolvent_of_productive
    (valuation : FLit → Prop) (provider source : FCL) (selected : FLit)
    (hprovider : ProductiveAt valuation provider selected)
    (hsource : FalseAt valuation source) :
    FalseAt valuation (resolvent provider source selected) := by
  constructor
  · intro literal hliteral
    simp only [resolvent, List.mem_append] at hliteral
    rcases hliteral with hliteral | hliteral
    · exact hprovider.body_true literal hliteral
    · exact hsource.1 literal (mem_without.mp hliteral).1
  · intro literal hliteral
    simp only [resolvent, List.mem_append] at hliteral
    rcases hliteral with hliteral | hliteral
    · have hwithout := mem_without.mp hliteral
      exact hprovider.other_false literal hwithout.1 hwithout.2
    · exact hsource.2 literal hliteral

theorem resolveProviders_falseAt
    (valuation : FLit → Prop) :
    ∀ {source providers conclusion},
      resolveProviders source providers = some conclusion →
      FalseAt valuation source →
      (∀ selected ∈ providers,
        ProductiveAt valuation selected.2 selected.1) →
      FalseAt valuation conclusion := by
  intro source providers
  induction providers generalizing source with
  | nil =>
      intro conclusion hresolve hsource _
      simp [resolveProviders] at hresolve
      subst conclusion
      exact hsource
  | cons selected providers ih =>
      rcases selected with ⟨literal, provider⟩
      intro conclusion hresolve hsource hproductive
      have hprovider := hproductive (literal, provider) (by simp)
      have htail : ∀ selected ∈ providers,
          ProductiveAt valuation selected.2 selected.1 := by
        intro selected hselected
        exact hproductive selected (by simp [hselected])
      by_cases hbody : literal ∈ source.body
      · simp only [resolveProviders, hbody, hprovider.selected_mem] at hresolve
        exact ih hresolve
          (hsource.resolvent_of_productive valuation provider source literal
            hprovider) htail
      · simp only [resolveProviders, hbody] at hresolve
        exact ih hresolve hsource htail

/-! ## Provider enumeration independent of runtime indexes -/

/-- A provider location is represented by ordinary naturals so the complete
enumeration remains directly serializable. -/
abbrev ProviderLocation := Nat × Nat

/-- Recompute every retained clause/head location whose literal is exactly the
requested body literal and whose head position is maximal in the checked
literal order. -/
def maximalProvidersFor (order : DecodedFiniteLiteralOrderDocument)
    (retained : List FCL) (literal : FLit) : List ProviderLocation :=
  (List.range retained.length).flatMap fun clauseIndex =>
    match retained[clauseIndex]? with
    | none => []
    | some provider =>
        ((order.maximalHeadIndices provider.head).filter fun headIndex =>
          decide (provider.head[headIndex]? = some literal)).map fun headIndex =>
            (clauseIndex, headIndex)

theorem mem_maximalProvidersFor_iff
    (order : DecodedFiniteLiteralOrderDocument)
    (retained : List FCL) (literal : FLit) (location : ProviderLocation) :
    location ∈ maximalProvidersFor order retained literal ↔
      location.1 < retained.length ∧
      ∃ provider, retained[location.1]? = some provider ∧
        location.2 ∈ order.maximalHeadIndices provider.head ∧
        provider.head[location.2]? = some literal := by
  rcases location with ⟨clauseIndex, headIndex⟩
  simp only [maximalProvidersFor, List.mem_flatMap, List.mem_range]
  constructor
  · rintro ⟨candidateIndex, hbound, hmember⟩
    cases hprovider : retained[candidateIndex]? with
    | none => simp [hprovider] at hmember
    | some provider =>
        simp only [hprovider, List.mem_map, List.mem_filter,
          decide_eq_true_eq] at hmember
        rcases hmember with ⟨selectedHead, ⟨hmaximal, hliteral⟩, heq⟩
        simp only [Prod.mk.injEq] at heq
        rcases heq with ⟨rfl, rfl⟩
        exact ⟨hbound, provider, hprovider, hmaximal, hliteral⟩
  · rintro ⟨hbound, provider, hprovider, hmaximal, hliteral⟩
    refine ⟨clauseIndex, hbound, ?_⟩
    simp only [hprovider, List.mem_map, List.mem_filter, decide_eq_true_eq]
    exact ⟨headIndex, ⟨hmaximal, hliteral⟩, rfl⟩

/-- Complete Cartesian provider locations for an instantiated source body. -/
def providerSelections (order : DecodedFiniteLiteralOrderDocument)
    (retained : List FCL) (body : List FLit) :
    List (List ProviderLocation) :=
  cartesianSelections (body.map (maximalProvidersFor order retained))

theorem mem_providerSelections_iff
    (order : DecodedFiniteLiteralOrderDocument)
    (retained : List FCL) (body : List FLit)
    (selection : List ProviderLocation) :
    selection ∈ providerSelections order retained body ↔
      Selects selection (body.map (maximalProvidersFor order retained)) := by
  exact mem_cartesianSelections_iff selection _

/-! ## Complete normalized candidates -/

/-- Decode one selected location and recheck that it contains the expected
literal. -/
def providerAt (retained : List FCL) (literal : FLit)
    (location : ProviderLocation) : Option (FLit × FCL) := do
  let provider ← retained[location.1]?
  let selected ← provider.head[location.2]?
  if selected = literal then some (literal, provider) else none

theorem providerAt_sound (retained : List FCL) (literal : FLit)
    (location : ProviderLocation) (selected : FLit × FCL)
    (hdecode : providerAt retained literal location = some selected) :
    selected.1 = literal ∧ selected.2 ∈ retained ∧
      literal ∈ selected.2.head := by
  rcases location with ⟨clauseIndex, headIndex⟩
  cases hprovider : retained[clauseIndex]? with
  | none => simp [providerAt, hprovider] at hdecode
  | some provider =>
      cases hhead : provider.head[headIndex]? with
      | none => simp [providerAt, hprovider, hhead] at hdecode
      | some headLiteral =>
          by_cases heq : headLiteral = literal
          · subst headLiteral
            simp [providerAt, hprovider, hhead] at hdecode
            cases hdecode
            exact ⟨rfl, (List.getElem?_eq_some_iff.mp hprovider).2 ▸
              List.getElem_mem (List.getElem?_eq_some_iff.mp hprovider).1,
              (List.getElem?_eq_some_iff.mp hhead).2 ▸
                List.getElem_mem (List.getElem?_eq_some_iff.mp hhead).1⟩
          · simp [providerAt, hprovider, hhead, heq] at hdecode

/-- Decode a provider location for every body literal, preserving body order. -/
def selectedProviders (retained : List FCL) :
    List FLit → List ProviderLocation → Option (List (FLit × FCL))
  | [], [] => some []
  | literal :: body, location :: locations => do
      let provider ← providerAt retained literal location
      let providers ← selectedProviders retained body locations
      return provider :: providers
  | _, _ => none

theorem selectedProviders_sound (retained : List FCL) :
    ∀ {body locations providers},
      selectedProviders retained body locations = some providers →
      providers.map Prod.fst = body ∧
      ∀ selected ∈ providers,
        selected.2 ∈ retained ∧ selected.1 ∈ selected.2.head := by
  intro body
  induction body with
  | nil =>
      intro locations providers hdecode
      cases locations with
      | nil =>
          simp [selectedProviders] at hdecode
          subst providers
          simp
      | cons location locations => simp [selectedProviders] at hdecode
  | cons literal body ih =>
      intro locations providers hdecode
      cases locations with
      | nil => simp [selectedProviders] at hdecode
      | cons location locations =>
          cases hprovider : providerAt retained literal location with
          | none => simp [selectedProviders, hprovider] at hdecode
          | some provider =>
              cases htail : selectedProviders retained body locations with
              | none => simp [selectedProviders, hprovider, htail] at hdecode
              | some tail =>
                  simp [selectedProviders, hprovider, htail] at hdecode
                  cases hdecode
                  have hproviderSound := providerAt_sound retained literal
                    location provider hprovider
                  have htailSound := ih htail
                  constructor
                  · simp [hproviderSound.1, htailSound.1]
                  · intro selected hselected
                    simp only [List.mem_cons] at hselected
                    rcases hselected with rfl | hselected
                    · exact ⟨hproviderSound.2.1, hproviderSound.1 ▸
                        hproviderSound.2.2⟩
                    · exact htailSound.2 selected hselected

/-- One fully checked Hyper candidate, including the same semantically relevant
head normalization used by the local closure layers. -/
def hyperCandidate? (retained : List FCL) (source : FCL)
    (substitution : List (Int × FTerm))
    (selection : List ProviderLocation) : Option FCL := do
  let instantiated := substCl substitution source
  let providers ← selectedProviders retained instantiated.body selection
  let raw ← resolveProviders instantiated providers
  let head ← normalizeGeneratedHead raw.head
  return { raw with head }

def hyperCandidates (order : DecodedFiniteLiteralOrderDocument)
    (terms : List FTerm) (retained source : List FCL) : List FCL :=
  source.flatMap fun sourceClause =>
    (substitutions terms sourceClause).flatMap fun substitution =>
      let instantiated := substCl substitution sourceClause
      (providerSelections order retained instantiated.body).filterMap fun selection =>
        hyperCandidate? retained sourceClause substitution selection

theorem hyperCandidate_sound {D : Type} (model : TModel D)
    (assignment : Int → D) (retained : List FCL) (source : FCL)
    (substitution : List (Int × FTerm)) (selection : List ProviderLocation)
    (conclusion : FCL)
    (hcandidate : hyperCandidate? retained source substitution selection =
      some conclusion)
    (hsource : valid model source)
    (hretained : ∀ clause ∈ retained, HoldsAt model assignment clause) :
    HoldsAt model assignment conclusion := by
  let instantiated := substCl substitution source
  cases hproviders : selectedProviders retained instantiated.body selection with
  | none => simp [hyperCandidate?, instantiated, hproviders] at hcandidate
  | some providers =>
      cases hraw : resolveProviders instantiated providers with
      | none =>
          simp [hyperCandidate?, instantiated, hproviders, hraw] at hcandidate
      | some raw =>
          cases hnormal : normalizeGeneratedHead raw.head with
          | none =>
              simp [hyperCandidate?, instantiated, hproviders, hraw, hnormal]
                at hcandidate
          | some head =>
              have hconclusion : { raw with head := head } = conclusion := by
                simpa [hyperCandidate?, instantiated, hproviders, hraw, hnormal]
                  using hcandidate
              rw [← hconclusion]
              apply HoldsAt.normalizeGeneratedHead_sound model assignment raw
                head hnormal
              apply resolveProviders_sound model assignment hraw
              · exact inst_valid model hsource substitution assignment
              · intro selected hselected
                have hdecoded := selectedProviders_sound retained hproviders
                exact hretained selected.2 (hdecoded.2 selected hselected).1

theorem hyperCandidates_sound {D : Type} (model : TModel D)
    (assignment : Int → D) (order : DecodedFiniteLiteralOrderDocument)
    (terms : List FTerm) (retained source : List FCL)
    (hsource : ∀ clause ∈ source, valid model clause)
    (hretained : ∀ clause ∈ retained, HoldsAt model assignment clause) :
    ∀ conclusion ∈ hyperCandidates order terms retained source,
      HoldsAt model assignment conclusion := by
  intro conclusion hconclusion
  simp only [hyperCandidates, List.mem_flatMap, List.mem_filterMap] at hconclusion
  obtain ⟨sourceClause, hsourceClause, substitution, hsubstitution,
    selection, hselection, hcandidate⟩ := hconclusion
  exact hyperCandidate_sound model assignment retained sourceClause substitution
    selection conclusion hcandidate (hsource sourceClause hsourceClause) hretained

example : substitutions [.const 0, .const 1]
    ⟨[.P (.concept 0 (.var 0))], [.P (.concept 1 (.var 0))]⟩ =
    [[(0, .const 0)], [(0, .const 1)]] := by native_decide

example : resolveProviders
    ⟨[.P (.concept 0 (.const 0))], [.P (.concept 1 (.const 0))]⟩
    [(.P (.concept 0 (.const 0)),
      ⟨[], [.P (.concept 0 (.const 0))]⟩)] =
    some ⟨[], [.P (.concept 1 (.const 0))]⟩ := by native_decide

/-- Regression: distinct body atoms may collapse to one literal after a
substitution. Resolving the first occurrence discharges all duplicates, and
the later checked selection is skipped rather than rejecting the candidate. -/
example :
    let a : FLit := .P (.concept 0 (.const 0))
    let b : FLit := .P (.concept 1 (.const 0))
    resolveProviders ⟨[a, a], [b]⟩ [(a, ⟨[], [a]⟩), (a, ⟨[], [a]⟩)] =
      some ⟨[], [b]⟩ := by native_decide

#print axioms substitutionOf_mem_substitutions
#print axioms substitutionOf_variables
#print axioms substitutionOf_terms_mem
#print axioms resolveProviders_sound
#print axioms resolveProviders_exists_of_provider_heads
#print axioms FalseAt.resolvent_of_productive
#print axioms resolveProviders_falseAt
#print axioms mem_maximalProvidersFor_iff
#print axioms mem_providerSelections_iff
#print axioms providerAt_sound
#print axioms selectedProviders_sound
#print axioms hyperCandidate_sound
#print axioms hyperCandidates_sound

end ContextCalculus.CBHyperClosure
