import ContextCalculus.Hypertableau

/-!
# Equality-premise normalization for hypertableau clauses

The Rust HT implementation removes positive equality atoms from clause bodies
and identifies their variables before constructing trigger indexes. This file
states and proves the semantic refinement used by that optimization. The proof
does not assume a particular union-find implementation: a certificate supplies
paths through equality premises and proves that every removed equality is
collapsed by the selected representative map.
-/

namespace ContextCalculus.Hypertableau

def Atom.rename (representative : Variable → Variable) :
    Atom Variable Concept Role → Atom Variable Concept Role
  | .concept literal node => .concept literal (representative node)
  | .role r source target =>
      .role r (representative source) (representative target)
  | .exists_ r filler node => .exists_ r filler (representative node)
  | .eq left right => .eq (representative left) (representative right)

@[simp] theorem Interp.satAtom_rename
    (I : Interp Domain Concept Role) (assignment : Variable → Domain)
    (representative : Variable → Variable) (atom : Atom Variable Concept Role) :
    I.satAtom assignment (atom.rename representative) ↔
      I.satAtom (assignment ∘ representative) atom := by
  cases atom <;> simp [Atom.rename, Interp.satAtom, Function.comp_apply]

def Atom.isEquality : Atom Variable Concept Role → Bool
  | .eq _ _ => true
  | _ => false

/-- Reflexive, symmetric, transitive connectivity generated by equality atoms
in a particular clause body. -/
inductive BodyEqualityPath (body : List (Atom Variable Concept Role)) :
    Variable → Variable → Prop
  | refl (v) : BodyEqualityPath body v v
  | premise {left right} (member : Atom.eq left right ∈ body) :
      BodyEqualityPath body left right
  | symm {left right} (path : BodyEqualityPath body left right) :
      BodyEqualityPath body right left
  | trans {left middle right}
      (first : BodyEqualityPath body left middle)
      (second : BodyEqualityPath body middle right) :
      BodyEqualityPath body left right

theorem BodyEqualityPath.assignment_eq
    {body : List (Atom Variable Concept Role)}
    (I : Interp Domain Concept Role) (assignment : Variable → Domain)
    (hbody : ∀ atom ∈ body, I.satAtom assignment atom)
    {left right : Variable} (path : BodyEqualityPath body left right) :
    assignment left = assignment right := by
  induction path with
  | refl => rfl
  | premise member => exact hbody _ member
  | symm _ ih => exact ih.symm
  | trans _ _ first second => exact first.trans second

/-- Evidence that `target` is obtained by quotienting all body variables along
positive equality premises, deleting those premises, and renaming every
remaining body and head atom. -/
structure BodyEqualityNormalization
    (source target : Clause Variable Concept Role) where
  representative : Variable → Variable
  representative_path : ∀ v,
    BodyEqualityPath source.body v (representative v)
  collapses_premise : ∀ left right,
    Atom.eq left right ∈ source.body →
      representative left = representative right
  target_body : target.body =
    (source.body.filter fun atom => !atom.isEquality).map
      (Atom.rename representative)
  target_head : target.head = source.head.map (Atom.rename representative)

private theorem BodyEqualityNormalization.assignment_representative
    {source target : Clause Variable Concept Role}
    (certificate : BodyEqualityNormalization source target)
    (I : Interp Domain Concept Role) (assignment : Variable → Domain)
    (hbody : ∀ atom ∈ source.body, I.satAtom assignment atom)
    (v : Variable) :
    assignment (certificate.representative v) = assignment v := by
  exact (certificate.representative_path v).assignment_eq I assignment hbody |>.symm

theorem BodyEqualityNormalization.modelsClause_iff
    {source target : Clause Variable Concept Role}
    (certificate : BodyEqualityNormalization source target)
    (I : Interp Domain Concept Role) :
    I.modelsClause source ↔ I.modelsClause target := by
  constructor
  · intro hsource assignment htargetBody
    let lifted := assignment ∘ certificate.representative
    have hliftedBody : ∀ atom ∈ source.body, I.satAtom lifted atom := by
      intro atom hatom
      cases atom with
      | eq left right =>
          exact congrArg assignment (certificate.collapses_premise left right hatom)
      | concept literal node =>
          apply (I.satAtom_rename assignment certificate.representative
            (.concept literal node)).mp
          apply htargetBody
          rw [certificate.target_body]
          exact List.mem_map.mpr ⟨_, List.mem_filter.mpr
            ⟨hatom, by simp [Atom.isEquality]⟩, rfl⟩
      | role role sourceNode targetNode =>
          apply (I.satAtom_rename assignment certificate.representative
            (.role role sourceNode targetNode)).mp
          apply htargetBody
          rw [certificate.target_body]
          exact List.mem_map.mpr ⟨_, List.mem_filter.mpr
            ⟨hatom, by simp [Atom.isEquality]⟩, rfl⟩
      | exists_ role filler node =>
          apply (I.satAtom_rename assignment certificate.representative
            (.exists_ role filler node)).mp
          apply htargetBody
          rw [certificate.target_body]
          exact List.mem_map.mpr ⟨_, List.mem_filter.mpr
            ⟨hatom, by simp [Atom.isEquality]⟩, rfl⟩
    rcases hsource lifted hliftedBody with ⟨atom, hatom, hsat⟩
    refine ⟨atom.rename certificate.representative, ?_, ?_⟩
    · rw [certificate.target_head]
      exact List.mem_map.mpr ⟨atom, hatom, rfl⟩
    · exact (I.satAtom_rename assignment certificate.representative atom).mpr hsat
  · intro htarget assignment hsourceBody
    have hassignment : assignment ∘ certificate.representative = assignment := by
      funext v
      exact certificate.assignment_representative I assignment hsourceBody v
    have htargetBody : ∀ atom ∈ target.body, I.satAtom assignment atom := by
      intro atom hatom
      rw [certificate.target_body] at hatom
      rcases List.mem_map.mp hatom with ⟨sourceAtom, hsourceAtom, rfl⟩
      apply (I.satAtom_rename assignment certificate.representative sourceAtom).mpr
      rw [hassignment]
      apply hsourceBody sourceAtom
      exact (List.mem_filter.mp hsourceAtom).1
    rcases htarget assignment htargetBody with ⟨atom, hatom, hsat⟩
    rw [certificate.target_head] at hatom
    rcases List.mem_map.mp hatom with ⟨sourceAtom, hsourceAtom, rfl⟩
    refine ⟨sourceAtom, hsourceAtom, ?_⟩
    rw [Interp.satAtom_rename, hassignment] at hsat
    exact hsat

theorem BodyEqualityNormalization.models_iff
    {source target : List (Clause Variable Concept Role)}
    (certificates : List
      (Σ pair : Clause Variable Concept Role × Clause Variable Concept Role,
        BodyEqualityNormalization pair.1 pair.2))
    (hsource : source = certificates.map fun certificate => certificate.1.1)
    (htarget : target = certificates.map fun certificate => certificate.1.2)
    (I : Interp Domain Concept Role) :
    I.models source ↔ I.models target := by
  subst source
  subst target
  constructor <;> intro hmodels clause hclause
  · rcases List.mem_map.mp hclause with ⟨certificate, hcertificate, rfl⟩
    exact (certificate.2.modelsClause_iff I).mp
      (hmodels certificate.1.1 (List.mem_map.mpr ⟨certificate, hcertificate, rfl⟩))
  · rcases List.mem_map.mp hclause with ⟨certificate, hcertificate, rfl⟩
    exact (certificate.2.modelsClause_iff I).mpr
      (hmodels certificate.1.2 (List.mem_map.mpr ⟨certificate, hcertificate, rfl⟩))

#print axioms BodyEqualityNormalization.modelsClause_iff
#print axioms BodyEqualityNormalization.models_iff

end ContextCalculus.Hypertableau
