import ContextCalculus.HypertableauEqualityModel
import ContextCalculus.HypertableauRefutationCertificate

/-!
# Finite equality-aware hypertableau refutation certificates

The certificate retains every asserted node-equality pair. Its semantic node
relation is the equivalence closure generated by that history. This deliberately
keeps union-find and representative choices out of the trusted format: a later
optimized checker may supply a proved refinement to the same closure.
-/

namespace ContextCalculus.Hypertableau

structure FiniteEqCertificate
    (nodeCount conceptCount roleCount variableCount : Nat) where
  base : FiniteSatCertificate nodeCount conceptCount roleCount variableCount
  equalities : List (Fin nodeCount × Fin nodeCount)
  representative : Fin nodeCount → Fin nodeCount
  representativePath : Fin nodeCount → List (Fin nodeCount)

def FiniteEqCertificate.state
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) :
    EqState (Fin nodeCount) (Fin conceptCount) (Fin roleCount) where
  base := certificate.base.state
  equiv := Relation.EqvGen fun x y => (x, y) ∈ certificate.equalities
  equiv_equivalence := Relation.EqvGen.is_equivalence _

private theorem eqvGen_cons_iff
    (pair : Node × Node) (pairs : List (Node × Node)) (x y : Node) :
    Relation.EqvGen (fun a b => (a, b) ∈ pair :: pairs) x y ↔
      Relation.EqvGen
        (fun a b => Relation.EqvGen (fun c d => (c, d) ∈ pairs) a b ∨
          (a = pair.1 ∧ b = pair.2)) x y := by
  constructor
  · intro hxy
    induction hxy with
    | rel a b h =>
        rcases List.mem_cons.mp h with hpair | hold
        · have ha : a = pair.1 := congrArg Prod.fst hpair
          have hb : b = pair.2 := congrArg Prod.snd hpair
          exact Relation.EqvGen.rel _ _ (Or.inr ⟨ha, hb⟩)
        · exact Relation.EqvGen.rel _ _
            (Or.inl (Relation.EqvGen.rel _ _ hold))
    | refl a => exact Relation.EqvGen.refl a
    | symm a b _ ih => exact Relation.EqvGen.symm _ _ ih
    | trans a b c _ _ hab hbc => exact Relation.EqvGen.trans _ _ _ hab hbc
  · intro hxy
    induction hxy with
    | rel a b h =>
        rcases h with hold | ⟨rfl, rfl⟩
        · induction hold with
          | rel c d hmem =>
              exact Relation.EqvGen.rel _ _ (List.mem_cons_of_mem _ hmem)
          | refl c => exact Relation.EqvGen.refl c
          | symm c d _ ih => exact Relation.EqvGen.symm _ _ ih
          | trans c d e _ _ hcd hde =>
              exact Relation.EqvGen.trans _ _ _ hcd hde
        · exact Relation.EqvGen.rel _ _ (List.mem_cons_self)
    | refl a => exact Relation.EqvGen.refl a
    | symm a b _ ih => exact Relation.EqvGen.symm _ _ ih
    | trans a b c _ _ hab hbc => exact Relation.EqvGen.trans _ _ _ hab hbc

def equalityStepB (equalities : List (Fin nodeCount × Fin nodeCount))
    (left right : Fin nodeCount) : Bool :=
  decide ((left, right) ∈ equalities) || decide ((right, left) ∈ equalities)

def equalityPathB (equalities : List (Fin nodeCount × Fin nodeCount))
    (target : Fin nodeCount) : Fin nodeCount → List (Fin nodeCount) → Bool
  | current, [] => decide (current = target)
  | current, next :: rest =>
      equalityStepB equalities current next && equalityPathB equalities target next rest

theorem equalityStepB_sound
    (equalities : List (Fin nodeCount × Fin nodeCount)) (left right : Fin nodeCount) :
    equalityStepB equalities left right = true →
      Relation.EqvGen (fun x y => (x, y) ∈ equalities) left right := by
  simp only [equalityStepB, Bool.or_eq_true, decide_eq_true_eq]
  intro h
  rcases h with hforward | hreverse
  · exact Relation.EqvGen.rel _ _ hforward
  · exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ hreverse)

theorem equalityPathB_sound
    (equalities : List (Fin nodeCount × Fin nodeCount))
    (source target : Fin nodeCount) (path : List (Fin nodeCount)) :
    equalityPathB equalities target source path = true →
      Relation.EqvGen (fun x y => (x, y) ∈ equalities) source target := by
  induction path generalizing source with
  | nil =>
      simp only [equalityPathB, decide_eq_true_eq]
      rintro rfl
      exact Relation.EqvGen.refl _
  | cons next rest ih =>
      simp only [equalityPathB, Bool.and_eq_true]
      rintro ⟨hstep, hrest⟩
      exact Relation.EqvGen.trans _ _ _
        (equalityStepB_sound equalities source next hstep) (ih next hrest)

/-- Executable validation that the supplied representative map is exactly the
equivalence closure generated by `equalities`. Each node supplies a checked
path to its representative; every generator must preserve representatives. -/
def FiniteEqCertificate.equalityClosureValidB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) : Bool :=
  (certificate.equalities.all fun pair =>
      decide (certificate.representative pair.1 = certificate.representative pair.2)) &&
  (List.finRange nodeCount).all fun node =>
    equalityPathB certificate.equalities (certificate.representative node) node
      (certificate.representativePath node)

theorem FiniteEqCertificate.equalityClosureValidB_sound
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true) (left right : Fin nodeCount) :
    certificate.state.equiv left right ↔
      certificate.representative left = certificate.representative right := by
  simp only [FiniteEqCertificate.equalityClosureValidB, List.all_eq_true,
    Bool.and_eq_true, decide_eq_true_eq] at hvalid
  rcases hvalid with ⟨hedges, hpaths⟩
  constructor
  · intro hequiv
    induction hequiv with
    | rel x y hxy => exact hedges (x, y) hxy
    | refl x => rfl
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ hxy hyz => exact hxy.trans hyz
  · intro hrepresentative
    have hleft := equalityPathB_sound certificate.equalities left
      (certificate.representative left) (certificate.representativePath left)
      (hpaths left (List.mem_finRange left))
    have hright := equalityPathB_sound certificate.equalities right
      (certificate.representative right) (certificate.representativePath right)
      (hpaths right (List.mem_finRange right))
    rw [hrepresentative] at hleft
    exact Relation.EqvGen.trans _ _ _ hleft (Relation.EqvGen.symm _ _ hright)

def FiniteEqCertificate.closedRelatedB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (left right : Fin nodeCount) : Bool :=
  decide (certificate.representative left = certificate.representative right)

theorem FiniteEqCertificate.closedRelatedB_eq_true
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true) (left right : Fin nodeCount) :
    certificate.closedRelatedB left right = true ↔ certificate.state.equiv left right := by
  rw [certificate.equalityClosureValidB_sound hvalid]
  simp [FiniteEqCertificate.closedRelatedB]

def FiniteEqCertificate.closedHoldsAtomB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount) :
    Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount) → Bool
  | .eq left right => certificate.closedRelatedB (assignment left) (assignment right)
  | atom => certificate.base.holdsAtomB assignment atom

theorem FiniteEqCertificate.closedHoldsAtomB_eq_true
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) :
    certificate.closedHoldsAtomB assignment atom = true ↔
      certificate.state.holdsAtom assignment atom := by
  cases atom with
  | concept lit node =>
      simpa [FiniteEqCertificate.closedHoldsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        certificate.base.holdsAtomB_eq_true assignment (.concept lit node)
  | role role source target =>
      simpa [FiniteEqCertificate.closedHoldsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        certificate.base.holdsAtomB_eq_true assignment (.role role source target)
  | exists_ role filler node =>
      simpa [FiniteEqCertificate.closedHoldsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        certificate.base.holdsAtomB_eq_true assignment (.exists_ role filler node)
  | eq left right =>
      exact certificate.closedRelatedB_eq_true hvalid (assignment left) (assignment right)

/-- Quotient-closed lookup used by positive equality-aware model certificates.
Unlike refutation-tree matching above, every fact kind is transported across
the complete node equivalence relation. -/
def FiniteEqCertificate.quotientHoldsAtomB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount) :
    Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount) → Bool
  | .concept lit node =>
      (List.finRange nodeCount).any fun source =>
        certificate.closedRelatedB source (assignment node) &&
          decide ((source, lit) ∈ certificate.base.labels)
  | .role role source target =>
      (List.finRange nodeCount).any fun edgeSource =>
        (List.finRange nodeCount).any fun edgeTarget =>
          (certificate.closedRelatedB edgeSource (assignment source) &&
            certificate.closedRelatedB edgeTarget (assignment target)) &&
          decide ((role, edgeSource, edgeTarget) ∈ certificate.base.edges)
  | .exists_ role filler node =>
      (List.finRange nodeCount).any fun source =>
        certificate.closedRelatedB source (assignment node) &&
          decide ((role, filler, source) ∈ certificate.base.obligations)
  | .eq left right => certificate.closedRelatedB (assignment left) (assignment right)

theorem FiniteEqCertificate.quotientHoldsAtomB_eq_true
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) :
    certificate.quotientHoldsAtomB assignment atom = true ↔
      certificate.state.closedHoldsAtom assignment atom := by
  cases atom with
  | concept lit node =>
      simp only [FiniteEqCertificate.quotientHoldsAtomB, List.any_eq_true,
        Bool.and_eq_true, decide_eq_true_eq, EqState.closedHoldsAtom,
        EqState.closedLabel]
      constructor
      · rintro ⟨source, _, hrelated, hlabel⟩
        exact ⟨source,
          (certificate.closedRelatedB_eq_true hvalid source (assignment node)).mp hrelated,
          hlabel⟩
      · rintro ⟨source, hrelated, hlabel⟩
        exact ⟨source, List.mem_finRange source,
          (certificate.closedRelatedB_eq_true hvalid source (assignment node)).mpr hrelated,
          hlabel⟩
  | role role source target =>
      simp only [FiniteEqCertificate.quotientHoldsAtomB, List.any_eq_true,
        Bool.and_eq_true, decide_eq_true_eq, EqState.closedHoldsAtom,
        EqState.closedEdge]
      constructor
      · rintro ⟨edgeSource, _, edgeTarget, _, ⟨hsource, htarget⟩, hedge⟩
        exact ⟨edgeSource, edgeTarget,
          (certificate.closedRelatedB_eq_true hvalid edgeSource (assignment source)).mp hsource,
          (certificate.closedRelatedB_eq_true hvalid edgeTarget (assignment target)).mp htarget,
          hedge⟩
      · rintro ⟨edgeSource, edgeTarget, hsource, htarget, hedge⟩
        exact ⟨edgeSource, List.mem_finRange edgeSource, edgeTarget,
          List.mem_finRange edgeTarget,
          ⟨(certificate.closedRelatedB_eq_true hvalid edgeSource (assignment source)).mpr hsource,
            (certificate.closedRelatedB_eq_true hvalid edgeTarget (assignment target)).mpr htarget⟩,
          hedge⟩
  | exists_ role filler node =>
      simp only [FiniteEqCertificate.quotientHoldsAtomB, List.any_eq_true,
        Bool.and_eq_true, decide_eq_true_eq, EqState.closedHoldsAtom,
        EqState.closedObligation]
      constructor
      · rintro ⟨source, _, hrelated, hobligation⟩
        exact ⟨source,
          (certificate.closedRelatedB_eq_true hvalid source (assignment node)).mp hrelated,
          hobligation⟩
      · rintro ⟨source, hrelated, hobligation⟩
        exact ⟨source, List.mem_finRange source,
          (certificate.closedRelatedB_eq_true hvalid source (assignment node)).mpr hrelated,
          hobligation⟩
  | eq left right =>
      simpa [EqState.closedHoldsAtom] using
        certificate.closedRelatedB_eq_true hvalid (assignment left) (assignment right)

def FiniteEqCertificate.closedClashB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) : Bool :=
  certificate.base.labels.any fun positive =>
    !positive.2.neg &&
      certificate.base.labels.any fun negative =>
        negative.2.neg && decide (positive.2.concept = negative.2.concept) &&
          certificate.closedRelatedB positive.1 negative.1

theorem FiniteEqCertificate.closedClashB_sound
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true) :
    certificate.closedClashB = true →
      ∃ positiveNode negativeNode concept,
        certificate.state.equiv positiveNode negativeNode ∧
        certificate.state.base.label positiveNode (.pos concept) ∧
        certificate.state.base.label negativeNode (.negated concept) := by
  intro hclash
  simp only [FiniteEqCertificate.closedClashB, List.any_eq_true, Bool.and_eq_true,
    decide_eq_true_eq] at hclash
  rcases hclash with
    ⟨⟨positiveNode, positiveLit⟩, hpositiveMem, hpositiveSign,
      ⟨⟨negativeNode, negativeLit⟩, hnegativeMem,
        ⟨⟨hnegativeSign, hconcept⟩, hrelated⟩⟩⟩
  rcases positiveLit with ⟨positiveConcept, positiveNeg⟩
  rcases negativeLit with ⟨negativeConcept, negativeNeg⟩
  have hp : positiveNeg = false := by cases positiveNeg <;> simp_all
  have hn : negativeNeg = true := by cases negativeNeg <;> simp_all
  subst positiveNeg
  subst negativeNeg
  simp only at hconcept hrelated
  rw [hconcept] at hpositiveMem
  exact ⟨positiveNode, negativeNode, negativeConcept,
    (certificate.closedRelatedB_eq_true hvalid positiveNode negativeNode).mp hrelated,
    hpositiveMem, hnegativeMem⟩

theorem FiniteEqCertificate.not_closedClashB_closedClashFree
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true)
    (hclash : certificate.closedClashB = false) :
    certificate.state.ClosedClashFree := by
  intro positiveNode negativeNode concept hrelated hlabels
  have hrelatedB : certificate.closedRelatedB positiveNode negativeNode = true :=
    (certificate.closedRelatedB_eq_true hvalid positiveNode negativeNode).mpr hrelated
  have hdetected : certificate.closedClashB = true := by
    simp only [FiniteEqCertificate.closedClashB, List.any_eq_true,
      Bool.and_eq_true, decide_eq_true_eq]
    exact ⟨(positiveNode, .pos concept), hlabels.1, by simp [Lit.pos],
      (negativeNode, .negated concept), hlabels.2,
      by simp [Lit.pos, Lit.negated],
      hrelatedB⟩
  rw [hdetected] at hclash
  contradiction

def FiniteEqCertificate.checkEqSat
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) : Bool :=
  certificate.equalityClosureValidB &&
  certificate.base.ontology.all (fun clause => clause.body.all atomGuardedB) &&
  !certificate.closedClashB &&
  certificate.base.obligations.all (fun obligation =>
    (List.finRange nodeCount).any fun witness =>
      decide ((obligation.1, obligation.2.2, witness) ∈ certificate.base.edges) &&
      decide ((witness, obligation.2.1) ∈ certificate.base.labels)) &&
  certificate.base.ontology.all (fun clause =>
    (allAssignments nodeCount variableCount).all fun assignment =>
      !(clause.body.all (certificate.quotientHoldsAtomB assignment)) ||
        clause.head.any (certificate.quotientHoldsAtomB assignment))

theorem FiniteEqCertificate.checkEqSat_models
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hcheck : certificate.checkEqSat = true) :
    certificate.state.quotientCanonical.models certificate.base.ontology := by
  simp only [FiniteEqCertificate.checkEqSat, Bool.and_eq_true,
    List.all_eq_true] at hcheck
  rcases hcheck with ⟨⟨⟨⟨hvalid, hguarded⟩, hclash⟩, hwitness⟩, hsaturated⟩
  apply certificate.state.quotientCanonical_models_of_closed_saturated
  · intro clause hclause atom hatom
    have h := hguarded clause hclause atom hatom
    cases atom with
    | concept lit node =>
        rcases lit with ⟨concept, neg⟩
        cases neg <;> simp [atomGuardedB, BodyAtom] at h ⊢
    | role => trivial
    | exists_ => simp [atomGuardedB] at h
    | eq => trivial
  · have hclashFalse : certificate.closedClashB = false := by
      simpa using hclash
    exact certificate.not_closedClashB_closedClashFree hvalid hclashFalse
  · intro node role filler hobligation
    have h := hwitness (role, filler, node) hobligation
    simp only [List.any_eq_true, Bool.and_eq_true, decide_eq_true_eq] at h
    rcases h with ⟨witness, _, hedge, hlabel⟩
    exact ⟨witness, hedge, hlabel⟩
  · intro clause hclause assignment hbody
    have hassignment : assignment ∈ allAssignments nodeCount variableCount :=
      mem_allAssignments nodeCount variableCount assignment
    have h := hsaturated clause hclause assignment hassignment
    have hbodyB : clause.body.all
        (certificate.quotientHoldsAtomB assignment) = true := by
      simp only [List.all_eq_true]
      intro atom hatom
      exact (certificate.quotientHoldsAtomB_eq_true hvalid assignment atom).mpr
        (hbody atom hatom)
    have hhead : clause.head.any
        (certificate.quotientHoldsAtomB assignment) = true := by
      simpa [hbodyB] using h
    rw [List.any_eq_true] at hhead
    rcases hhead with ⟨atom, hatom, hholds⟩
    exact ⟨atom, hatom,
      (certificate.quotientHoldsAtomB_eq_true hvalid assignment atom).mp hholds⟩

theorem FiniteEqCertificate.checkEqSat_satisfiable
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hcheck : certificate.checkEqSat = true) :
    ∃ (Domain : Type) (I : Interp Domain (Fin conceptCount) (Fin roleCount)),
      I.models certificate.base.ontology :=
  ⟨certificate.state.QuotientDomain, certificate.state.quotientCanonical,
    certificate.checkEqSat_models hcheck⟩

theorem FiniteEqCertificate.checkEqSat_not_entailsSub
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (sub sup : Fin conceptCount)
    (hsub : (root, .pos sub) ∈ certificate.base.labels)
    (hnotSup : (root, .negated sup) ∈ certificate.base.labels)
    (hcheck : certificate.checkEqSat = true) :
    ¬EntailsSub certificate.base.ontology sub sup := by
  intro hentails
  have hmodels := certificate.checkEqSat_models hcheck
  have hparts := hcheck
  simp only [FiniteEqCertificate.checkEqSat, Bool.and_eq_true] at hparts
  have hvalid : certificate.equalityClosureValidB = true := by
    exact hparts.1.1.1.1
  have hclashFalse : certificate.closedClashB = false := by
    simpa using hparts.1.1.2
  have hclash := certificate.not_closedClashB_closedClashFree hvalid hclashFalse
  let value : certificate.state.QuotientDomain :=
    Quotient.mk certificate.state.nodeSetoid root
  have hsubModel : certificate.state.quotientCanonical.concept sub value :=
    ⟨root, rfl, hsub⟩
  have hsupModel := hentails _ certificate.state.quotientCanonical hmodels value hsubModel
  have hnegative := certificate.state.quotientCanonical_sat_closedLabel hclash
    root (.negated sup) ⟨root, certificate.state.equiv_equivalence.1 root, hnotSup⟩
  exact hnegative hsupModel

theorem FiniteEqCertificate.checkEqSat_not_unsatisfiableConcept
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (concept : Fin conceptCount)
    (hconcept : (root, .pos concept) ∈ certificate.base.labels)
    (hcheck : certificate.checkEqSat = true) :
    ¬UnsatisfiableConcept certificate.base.ontology concept := by
  intro hunsatisfiable
  have hmodels := certificate.checkEqSat_models hcheck
  let value : certificate.state.QuotientDomain :=
    Quotient.mk certificate.state.nodeSetoid root
  exact hunsatisfiable _ certificate.state.quotientCanonical hmodels value
    ⟨root, rfl, hconcept⟩

def FiniteEqCertificate.freshNodeB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (target : Fin nodeCount) : Bool :=
  certificate.base.freshNodeB target &&
    (List.finRange nodeCount).all fun node =>
      decide (certificate.representative target ≠ certificate.representative node) ||
        decide (node = target)

theorem FiniteEqCertificate.freshNodeB_eq_true
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hvalid : certificate.equalityClosureValidB = true) (target : Fin nodeCount) :
    certificate.freshNodeB target = true ↔ certificate.state.Fresh target := by
  simp only [FiniteEqCertificate.freshNodeB, Bool.and_eq_true, List.all_eq_true,
    Bool.or_eq_true, decide_eq_true_eq, EqState.Fresh]
  constructor
  · rintro ⟨hbase, hisolated⟩
    refine ⟨(certificate.base.freshNodeB_eq_true target).mp hbase, ?_⟩
    intro node hequiv
    rcases hisolated node (List.mem_finRange node) with hnot | heq
    · exact (hnot ((certificate.equalityClosureValidB_sound hvalid target node).mp hequiv)).elim
    · exact heq
  · rintro ⟨hbase, hisolated⟩
    refine ⟨(certificate.base.freshNodeB_eq_true target).mpr hbase, ?_⟩
    intro node _
    by_cases hequiv : certificate.state.equiv target node
    · exact Or.inr (hisolated node hequiv)
    · exact Or.inl (fun hrepresentative => hequiv
        ((certificate.equalityClosureValidB_sound hvalid target node).mpr hrepresentative))

def FiniteEqCertificate.materializeWitness
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (source target : Fin nodeCount) (role : Fin roleCount)
    (filler : Lit (Fin conceptCount)) :
    FiniteEqCertificate nodeCount conceptCount roleCount variableCount :=
  { certificate with base := certificate.base.materializeWitness source target role filler }

theorem FiniteEqCertificate.state_materializeWitness
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (source target : Fin nodeCount) (role : Fin roleCount)
    (filler : Lit (Fin conceptCount)) :
    (certificate.materializeWitness source target role filler).state =
      certificate.state.materializeWitness source target role filler := by
  apply EqState.ext
  · exact certificate.base.state_materializeWitness source target role filler
  · rfl

def FiniteEqCertificate.assertAtom
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount) :
    Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount) →
      FiniteEqCertificate nodeCount conceptCount roleCount variableCount
  | .eq left right =>
      { certificate with
        equalities := (assignment left, assignment right) :: certificate.equalities }
  | atom => { certificate with base := certificate.base.assertAtom assignment atom }

theorem FiniteEqCertificate.state_assertAtom
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) :
    (certificate.assertAtom assignment atom).state =
      certificate.state.assertAtom assignment atom := by
  cases atom with
  | concept lit node =>
      apply EqState.ext
      · simpa [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom] using
          certificate.base.state_assertAtom assignment (.concept lit node)
      · simp [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom]
  | role role source target =>
      apply EqState.ext
      · simpa [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom] using
          certificate.base.state_assertAtom assignment (.role role source target)
      · simp [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom]
  | exists_ role filler node =>
      apply EqState.ext
      · simpa [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom] using
          certificate.base.state_assertAtom assignment (.exists_ role filler node)
      · simp [FiniteEqCertificate.assertAtom, FiniteEqCertificate.state,
          EqState.assertAtom]
  | eq left right =>
      apply EqState.ext
      · rfl
      · funext x y
        apply propext
        exact eqvGen_cons_iff (assignment left, assignment right)
          certificate.equalities x y

def FiniteEqCertificate.holdsAtomB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount) :
    Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount) → Bool
  | .eq left right =>
      decide (assignment left = assignment right) ||
      decide ((assignment left, assignment right) ∈ certificate.equalities) ||
      decide ((assignment right, assignment left) ∈ certificate.equalities)
  | atom => certificate.base.holdsAtomB assignment atom

theorem FiniteEqCertificate.holdsAtomB_sound
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) :
    certificate.holdsAtomB assignment atom = true →
      certificate.state.holdsAtom assignment atom := by
  cases atom with
  | concept lit node =>
      simpa [FiniteEqCertificate.holdsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        (certificate.base.holdsAtomB_eq_true assignment (.concept lit node)).mp
  | role role source target =>
      simpa [FiniteEqCertificate.holdsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        (certificate.base.holdsAtomB_eq_true assignment (.role role source target)).mp
  | exists_ role filler node =>
      simpa [FiniteEqCertificate.holdsAtomB, FiniteEqCertificate.state,
        EqState.holdsAtom] using
        (certificate.base.holdsAtomB_eq_true assignment (.exists_ role filler node)).mp
  | eq left right =>
      simp only [FiniteEqCertificate.holdsAtomB, Bool.or_eq_true,
        decide_eq_true_eq]
      intro h
      rcases h with hfirst | hreverse
      · rcases hfirst with heq | hforward
        · change certificate.state.equiv (assignment left) (assignment right)
          rw [heq]
          exact Relation.EqvGen.refl _
        · exact Relation.EqvGen.rel _ _ hforward
      · exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ hreverse)

def FiniteEqCertificate.relatedB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (left right : Fin nodeCount) : Bool :=
  decide (left = right) || decide ((left, right) ∈ certificate.equalities) ||
    decide ((right, left) ∈ certificate.equalities)

theorem FiniteEqCertificate.relatedB_sound
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (left right : Fin nodeCount) :
    certificate.relatedB left right = true → certificate.state.equiv left right := by
  simp only [FiniteEqCertificate.relatedB, Bool.or_eq_true, decide_eq_true_eq]
  intro h
  rcases h with hfirst | hreverse
  · rcases hfirst with heq | hforward
    · rw [heq]
      exact Relation.EqvGen.refl _
    · exact Relation.EqvGen.rel _ _ hforward
  · exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ hreverse)

def FiniteEqCertificate.clashB
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) : Bool :=
  certificate.base.labels.any fun positive =>
    !positive.2.neg &&
      certificate.base.labels.any fun negative =>
        negative.2.neg && decide (positive.2.concept = negative.2.concept) &&
          certificate.relatedB positive.1 negative.1

theorem FiniteEqCertificate.clashB_sound
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) :
    certificate.clashB = true →
      ∃ positiveNode negativeNode concept,
        certificate.state.equiv positiveNode negativeNode ∧
        certificate.state.base.label positiveNode (.pos concept) ∧
        certificate.state.base.label negativeNode (.negated concept) := by
  intro hclash
  simp only [FiniteEqCertificate.clashB, List.any_eq_true, Bool.and_eq_true,
    decide_eq_true_eq] at hclash
  rcases hclash with
    ⟨⟨positiveNode, positiveLit⟩, hpositiveMem, hpositiveSign,
      ⟨⟨negativeNode, negativeLit⟩, hnegativeMem,
        ⟨⟨hnegativeSign, hconcept⟩, hrelated⟩⟩⟩
  rcases positiveLit with ⟨positiveConcept, positiveNeg⟩
  rcases negativeLit with ⟨negativeConcept, negativeNeg⟩
  have hp : positiveNeg = false := by
    cases positiveNeg <;> simp_all
  have hn : negativeNeg = true := by
    cases negativeNeg <;> simp_all
  subst positiveNeg
  subst negativeNeg
  simp only at hconcept hrelated
  rw [hconcept] at hpositiveMem
  exact ⟨positiveNode, negativeNode, negativeConcept,
    certificate.relatedB_sound positiveNode negativeNode hrelated,
    hpositiveMem, hnegativeMem⟩

def FiniteEqCertificate.transitionB
    (current next : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) : Bool :=
  decide (next.base.ontology = (current.assertAtom assignment atom).base.ontology) &&
  decide (next.base.labels = (current.assertAtom assignment atom).base.labels) &&
  decide (next.base.edges = (current.assertAtom assignment atom).base.edges) &&
  decide (next.base.obligations = (current.assertAtom assignment atom).base.obligations) &&
  decide (next.equalities = (current.assertAtom assignment atom).equalities)

theorem FiniteEqCertificate.transitionB_base
    (current next : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount))
    (htransition : current.transitionB next assignment atom = true) :
    next.base = (current.assertAtom assignment atom).base := by
  simp only [FiniteEqCertificate.transitionB, Bool.and_eq_true,
    decide_eq_true_eq] at htransition
  rcases htransition with ⟨⟨⟨⟨hontology, hlabels⟩, hedges⟩, hobligations⟩, _⟩
  cases hnext : next.base with
  | mk nextOntology nextLabels nextEdges nextObligations =>
      cases hexpected : (current.assertAtom assignment atom).base with
      | mk expectedOntology expectedLabels expectedEdges expectedObligations =>
          simp only [hnext, hexpected] at hontology hlabels hedges hobligations
          subst expectedOntology
          subst expectedLabels
          subst expectedEdges
          subst expectedObligations
          rfl

theorem FiniteEqCertificate.transitionB_state
    (current next : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (assignment : Fin variableCount → Fin nodeCount)
    (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount))
    (htransition : current.transitionB next assignment atom = true) :
    next.state = current.state.assertAtom assignment atom := by
  have hbase := current.transitionB_base next assignment atom htransition
  have hequalities : next.equalities =
      (current.assertAtom assignment atom).equalities := by
    simp only [FiniteEqCertificate.transitionB, Bool.and_eq_true,
      decide_eq_true_eq] at htransition
    exact htransition.2
  rw [← current.state_assertAtom assignment atom]
  apply EqState.ext
  · exact congrArg FiniteSatCertificate.state hbase
  · simp only [FiniteEqCertificate.state]
    rw [hequalities]

mutual
  inductive FiniteEqRefutationTree
      (nodeCount conceptCount roleCount variableCount : Nat) where
    | clash
    | branch
        (clause : Clause (Fin variableCount) (Fin conceptCount) (Fin roleCount))
        (assignment : Fin variableCount → Fin nodeCount)
        (children : FiniteEqRefutationChildren nodeCount conceptCount roleCount variableCount)
    | witness
        (source target : Fin nodeCount) (role : Fin roleCount)
        (filler : Lit (Fin conceptCount))
        (child : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)

  inductive FiniteEqRefutationChildren
      (nodeCount conceptCount roleCount variableCount : Nat) where
    | nil
    | cons
        (atom : Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount))
        (next : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
        (child : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)
        (rest : FiniteEqRefutationChildren nodeCount conceptCount roleCount variableCount)
end

mutual
  def FiniteEqRefutationTree.check
      (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) :
      FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount → Bool
    | .clash => certificate.equalityClosureValidB && certificate.closedClashB
    | .branch clause assignment children =>
        certificate.equalityClosureValidB &&
        decide (clause ∈ certificate.base.ontology) &&
        clause.body.all (certificate.closedHoldsAtomB assignment) &&
        children.check certificate assignment clause.head
    | .witness source target role filler child =>
        certificate.equalityClosureValidB &&
        decide ((role, filler, source) ∈ certificate.base.obligations) &&
        certificate.freshNodeB target &&
        child.check (certificate.materializeWitness source target role filler)

  def FiniteEqRefutationChildren.check
      (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
      (assignment : Fin variableCount → Fin nodeCount) :
      FiniteEqRefutationChildren nodeCount conceptCount roleCount variableCount →
      List (Atom (Fin variableCount) (Fin conceptCount) (Fin roleCount)) → Bool
    | .nil, heads => heads.isEmpty
    | .cons .., [] => false
    | .cons atom next child rest, head :: heads =>
        decide (atom = head) && certificate.transitionB next assignment atom &&
        child.check next && rest.check certificate assignment heads
end

mutual
  theorem FiniteEqRefutationTree.check_sound
      (tree : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount) :
      ∀ certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount,
        tree.check certificate = true →
        EqRefutes (Fin nodeCount) certificate.base.ontology certificate.state := by
    cases tree with
    | clash =>
        intro certificate hcheck
        simp only [FiniteEqRefutationTree.check, Bool.and_eq_true] at hcheck
        exact EqRefutes.clash certificate.state
          (certificate.closedClashB_sound hcheck.1 hcheck.2)
    | branch clause assignment children =>
        intro certificate hcheck
        simp only [FiniteEqRefutationTree.check, Bool.and_eq_true,
          List.all_eq_true, decide_eq_true_eq] at hcheck
        rcases hcheck with ⟨⟨⟨hvalid, hclause⟩, hbody⟩, hchildren⟩
        apply EqRefutes.branch certificate.state clause hclause assignment
        · intro atom hatom
          exact (certificate.closedHoldsAtomB_eq_true hvalid assignment atom).mp
            (hbody atom hatom)
        · intro atom hatom
          exact children.check_sound certificate assignment clause.head hchildren atom hatom
    | witness source target role filler child =>
        intro certificate hcheck
        simp only [FiniteEqRefutationTree.check, Bool.and_eq_true,
          decide_eq_true_eq] at hcheck
        rcases hcheck with ⟨⟨⟨hvalid, hobligation⟩, hfresh⟩, hchild⟩
        apply EqRefutes.witness certificate.state source target role filler hobligation
          ((certificate.freshNodeB_eq_true hvalid target).mp hfresh)
        rw [← certificate.state_materializeWitness source target role filler]
        exact child.check_sound (certificate.materializeWitness source target role filler) hchild

  theorem FiniteEqRefutationChildren.check_sound
      (children : FiniteEqRefutationChildren nodeCount conceptCount roleCount variableCount) :
      ∀ (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
        (assignment : Fin variableCount → Fin nodeCount) (heads)
        (_ : children.check certificate assignment heads = true)
        (atom), atom ∈ heads →
          EqRefutes (Fin nodeCount) certificate.base.ontology
            (certificate.state.assertAtom assignment atom) := by
    cases children with
    | nil =>
        intro certificate assignment heads hcheck atom hatom
        simp only [FiniteEqRefutationChildren.check, List.isEmpty_iff] at hcheck
        simp [hcheck] at hatom
    | cons recorded next child rest =>
        intro certificate assignment heads hcheck atom hatom
        cases heads with
        | nil => simp at hatom
        | cons head heads =>
            simp only [FiniteEqRefutationChildren.check, Bool.and_eq_true,
              decide_eq_true_eq] at hcheck
            rcases hcheck with ⟨⟨⟨hrecorded, htransition⟩, hchild⟩, hrest⟩
            subst recorded
            simp only [List.mem_cons] at hatom
            rcases hatom with hatom | hatom
            · subst atom
              rw [← certificate.transitionB_state next assignment head htransition]
              have hbase := certificate.transitionB_base next assignment head htransition
              have hontology : next.base.ontology = certificate.base.ontology := by
                rw [hbase]
                cases head <;> rfl
              simpa only [hontology] using child.check_sound next hchild
            · exact rest.check_sound certificate assignment heads hrest atom hatom

end

theorem FiniteEqRefutationTree.check_unsatisfiable
    (tree : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hcheck : tree.check certificate = true) :
    ¬certificate.state.RealizableWith certificate.base.ontology :=
  (tree.check_sound certificate hcheck).sound

def FiniteEqCertificate.EmptyRoot
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount) : Prop :=
  certificate.base.labels = [] ∧ certificate.base.edges = [] ∧
    certificate.base.obligations = []

/-- A checked equality-aware refutation from an empty graph excludes every
nonempty-domain model of the exact ontology. A constant node valuation respects
any certified equality quotient, so no unique-name assumption is introduced. -/
theorem FiniteEqRefutationTree.check_ontology_unsatisfiable
    [Nonempty (Fin nodeCount)]
    (tree : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (hempty : certificate.EmptyRoot)
    (hcheck : tree.check certificate = true) :
    ¬∃ (Domain : Type) (I : Interp Domain (Fin conceptCount) (Fin roleCount)),
      Nonempty Domain ∧ I.models certificate.base.ontology := by
  rintro ⟨Domain, I, hdomain, hmodels⟩
  apply tree.check_unsatisfiable certificate hcheck
  let value : Fin nodeCount → Domain := fun _ => Classical.choice hdomain
  refine ⟨Domain, I, value, hmodels, ?_⟩
  rcases hempty with ⟨hlabels, hedges, hobligations⟩
  refine ⟨?_, ?_⟩
  · simp [FiniteEqCertificate.state, FiniteSatCertificate.state, State.RealizedBy,
      hlabels, hedges, hobligations]
  · intro left right _
    rfl

def FiniteEqCertificate.SubsumptionRoot
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (sub sup : Fin conceptCount) : Prop :=
  certificate.base.labels = [(root, .pos sub), (root, .negated sup)] ∧
  certificate.base.edges = [] ∧ certificate.base.obligations = []

def FiniteEqCertificate.UnsatisfiableRoot
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (concept : Fin conceptCount) : Prop :=
  certificate.base.labels = [(root, .pos concept)] ∧
  certificate.base.edges = [] ∧ certificate.base.obligations = []

theorem FiniteEqRefutationTree.check_subsumption
    (tree : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (sub sup : Fin conceptCount)
    (hroot : certificate.SubsumptionRoot root sub sup)
    (hcheck : tree.check certificate = true) :
    EntailsSub certificate.base.ontology sub sup := by
  intro Domain I hmodels value hsub
  by_contra hsup
  apply tree.check_unsatisfiable certificate hcheck
  refine ⟨Domain, I, fun _ => value, hmodels, ?_, ?_⟩
  · rcases hroot with ⟨hlabels, hedges, hobligations⟩
    refine ⟨?_, ?_, ?_⟩
    · intro node lit hlabel
      simp only [FiniteEqCertificate.state, FiniteSatCertificate.state, hlabels,
        List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at hlabel
      rcases hlabel with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · simpa [Interp.satLit, Lit.pos] using hsub
      · simpa [Interp.satLit, Lit.negated] using hsup
    · simp [FiniteEqCertificate.state, FiniteSatCertificate.state, hedges]
    · simp [FiniteEqCertificate.state, FiniteSatCertificate.state, hobligations]
  · intro left right _
    rfl

theorem FiniteEqRefutationTree.check_unsatisfiable_concept
    (tree : FiniteEqRefutationTree nodeCount conceptCount roleCount variableCount)
    (certificate : FiniteEqCertificate nodeCount conceptCount roleCount variableCount)
    (root : Fin nodeCount) (concept : Fin conceptCount)
    (hroot : certificate.UnsatisfiableRoot root concept)
    (hcheck : tree.check certificate = true) :
    UnsatisfiableConcept certificate.base.ontology concept := by
  intro Domain I hmodels value hconcept
  apply tree.check_unsatisfiable certificate hcheck
  refine ⟨Domain, I, fun _ => value, hmodels, ?_, ?_⟩
  · rcases hroot with ⟨hlabels, hedges, hobligations⟩
    refine ⟨?_, ?_, ?_⟩
    · intro node lit hlabel
      simp only [FiniteEqCertificate.state, FiniteSatCertificate.state, hlabels,
        List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at hlabel
      rcases hlabel with ⟨rfl, rfl⟩
      simpa [Interp.satLit, Lit.pos] using hconcept
    · simp [FiniteEqCertificate.state, FiniteSatCertificate.state, hedges]
    · simp [FiniteEqCertificate.state, FiniteSatCertificate.state, hobligations]
  · intro left right _
    rfl

namespace EqualityRefutationCheckerTests

private def transitiveBase : FiniteSatCertificate 3 1 1 1 where
  ontology := []
  labels := [(0, .pos 0), (2, .negated 0)]
  edges := []
  obligations := []

private def transitiveCertificate : FiniteEqCertificate 3 1 1 1 where
  base := transitiveBase
  equalities := [(0, 1), (1, 2)]
  representative := fun _ => 0
  representativePath := fun node =>
    if node = 0 then [] else if node = 1 then [0] else [1, 0]

example : transitiveCertificate.equalityClosureValidB = true := by native_decide
example : transitiveCertificate.closedRelatedB 0 2 = true := by native_decide
example : (FiniteEqRefutationTree.clash.check transitiveCertificate) = true := by
  native_decide

private def invalidTransitiveCertificate : FiniteEqCertificate 3 1 1 1 :=
  { transitiveCertificate with representativePath := fun _ => [] }

example : invalidTransitiveCertificate.equalityClosureValidB = false := by native_decide
example : (FiniteEqRefutationTree.clash.check invalidTransitiveCertificate) = false := by
  native_decide

private def equalityClause : Clause (Fin 3) (Fin 1) (Fin 1) :=
  { body := [], head := [.eq 0 2] }

private def equalityRootBase : FiniteSatCertificate 3 1 1 3 where
  ontology := [equalityClause]
  labels := [(0, .pos 0), (2, .negated 0)]
  edges := []
  obligations := []

private def equalityRoot : FiniteEqCertificate 3 1 1 3 where
  base := equalityRootBase
  equalities := []
  representative := id
  representativePath := fun _ => []

private def equalityChild : FiniteEqCertificate 3 1 1 3 where
  base := equalityRootBase
  equalities := [(0, 2)]
  representative := fun node => if node = 2 then 0 else node
  representativePath := fun node => if node = 2 then [0] else []

private def equalityBranch : FiniteEqRefutationTree 3 1 1 3 :=
  .branch equalityClause id
    (.cons (.eq 0 2) equalityChild .clash .nil)

example : equalityBranch.check equalityRoot = true := by native_decide

private def staleEqualityChild : FiniteEqCertificate 3 1 1 3 := equalityRoot

private def staleEqualityBranch : FiniteEqRefutationTree 3 1 1 3 :=
  .branch equalityClause id
    (.cons (.eq 0 2) staleEqualityChild .clash .nil)

example : staleEqualityBranch.check equalityRoot = false := by native_decide

end EqualityRefutationCheckerTests

namespace EqualitySatCheckerTests

private def quotientSat : FiniteEqCertificate 2 2 1 2 where
  base := {
    ontology := [
      { body := [.concept (.pos 0) 0], head := [.concept (.pos 1) 0] },
      { body := [], head := [.eq 0 1] }
    ]
    labels := [(1, .pos 0), (0, .pos 1)]
    edges := []
    obligations := []
  }
  equalities := [(0, 1)]
  representative := fun _ => 0
  representativePath := fun node => if node = 1 then [0] else []

example : quotientSat.checkEqSat = true := by native_decide

private def missingQuotientHead : FiniteEqCertificate 2 2 1 2 :=
  { quotientSat with base := { quotientSat.base with labels := [(1, .pos 0)] } }

example : missingQuotientHead.checkEqSat = false := by native_decide

private def quotientClash : FiniteEqCertificate 2 1 1 0 where
  base := {
    ontology := []
    labels := [(0, .pos 0), (1, .negated 0)]
    edges := []
    obligations := []
  }
  equalities := [(0, 1)]
  representative := fun _ => 0
  representativePath := fun node => if node = 1 then [0] else []

example : quotientClash.checkEqSat = false := by native_decide

end EqualitySatCheckerTests

#print axioms FiniteEqCertificate.equalityClosureValidB_sound
#print axioms FiniteEqCertificate.checkEqSat_models
#print axioms FiniteEqCertificate.checkEqSat_satisfiable
#print axioms FiniteEqCertificate.checkEqSat_not_entailsSub
#print axioms FiniteEqCertificate.checkEqSat_not_unsatisfiableConcept
#print axioms FiniteEqRefutationTree.check_sound
#print axioms FiniteEqRefutationTree.check_unsatisfiable
#print axioms FiniteEqRefutationTree.check_ontology_unsatisfiable
#print axioms FiniteEqRefutationTree.check_subsumption
#print axioms FiniteEqRefutationTree.check_unsatisfiable_concept

end ContextCalculus.Hypertableau
