import ContextCalculus.HypertableauRuntimeSearch
import ContextCalculus.HypertableauRegularCertificate

/-!
# Equality-free blocked-open regular certificate production

This module composes the concrete blocker-aware terminal selector with the
regular certificate producer boundary. The finite certificate retains the raw
saturated terminal graph. Existential witnesses are read at blocker redirects,
so certificate production neither copies edges nor creates new clause matches.
-/

namespace ContextCalculus.Hypertableau

/-! ## A proved local residual-clause boundary -/

def ConceptBodyAtom : Atom Variable Concept Role → Prop
  | .concept literal _ => literal.neg = false
  | _ => False

/-- A residual body is local to one directed forest edge: it contains only
positive concept tests, or positive concept tests plus one repeated syntactic
role atom between two distinct variables. This is the first production shape
for which redirected-cover grounding can be pulled back constructively. -/
def Clause.SingleDirectRoleBody
    (clause : Clause Variable Concept Role) : Prop :=
  (∀ atom ∈ clause.body, ConceptBodyAtom atom) ∨
  ∃ role source target, source ≠ target ∧
    Atom.role role source target ∈ clause.body ∧
    ∀ atom ∈ clause.body,
      atom = .role role source target ∨ ConceptBodyAtom atom

def Clause.SimpleBodyRoles
    (rules : UnravellingRoleRules Role)
    (clause : Clause Variable Concept Role) : Prop :=
  ∀ role source target, Atom.role role source target ∈ clause.body →
    rules.SyntacticallySimple role

/-- For a syntactically simple body role, every endpoint-cover edge is one raw
edge at the redirected source. Role-rule conclusions require a separate
closure-local theorem and are intentionally excluded from this boundary. -/
def State.DirectCoverForBody
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role) : Prop :=
  ∀ role sourceVariable targetVariable,
    Atom.role role sourceVariable targetVariable ∈ clause.body →
    ∀ source target, cover role source target →
    state.edge role (redirect source) target

/-- Every endpoint-cover fact is represented by a raw completion edge after
redirecting both finite endpoints. This condition is independent of residual
clause shape and accommodates inverse and chain closure when the redirect is a
role bisimulation. -/
def State.RedirectCoverFacts
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop) : Prop :=
  ∀ role source target, cover role source target →
    state.edge role (redirect source) (redirect target)

/-- Every serialized cover edge was generated by the endpoint-role closure;
the checker separately proves the converse closure inclusion. -/
def FiniteRegularCertificate.CoverGenerated
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount) : Prop :=
  ∀ role source target, certificate.coverRelation role source target →
    EndpointRole certificate.state certificate.redirect certificate.rules
      role source target

theorem FiniteRegularCertificate.directCoverForBody_of_generated
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (hgenerated : certificate.CoverGenerated)
    (clause : Clause (Fin variableCount) (Fin conceptCount) (Fin roleCount))
    (hsimple : clause.SimpleBodyRoles certificate.rules) :
    certificate.state.DirectCoverForBody certificate.redirect
      certificate.coverRelation clause := by
  intro role sourceVariable targetVariable hrole source target hcover
  exact (hgenerated role source target hcover).raw_of_syntacticallySimple
    (hsimple role sourceVariable targetVariable hrole)

/-- Pull a cover grounding of one local residual clause back to the raw
saturated completion state, then transfer its concept or existential head to
the original endpoint assignment. -/
theorem State.coverDischarges_of_singleDirectRoleBody
    [DecidableEq Variable]
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role)
    (hshape : clause.SingleDirectRoleBody)
    (hlocal : state.RedirectLocalFacts redirect)
    (hdirect : state.DirectCoverForBody redirect cover clause)
    (hheads : ∀ atom ∈ clause.head, PathLiftableHead atom)
    (hdischarges : state.Discharges clause) :
    state.CoverDischarges cover clause := by
  classical
  rcases hshape with hconcepts | ⟨role, source, target, hne, hrole, hbodyShape⟩
  · intro assignment hbody
    have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom assignment atom := by
      intro atom hatom
      cases atom with
      | concept literal node =>
          exact hbody (.concept literal node) hatom
      | role => exact (hconcepts _ hatom).elim
      | exists_ => exact (hconcepts _ hatom).elim
      | eq => exact (hconcepts _ hatom).elim
    rcases hdischarges assignment hrawBody with ⟨atom, hatom, hhead⟩
    refine ⟨atom, hatom, ?_⟩
    cases atom with
    | concept => exact hhead
    | exists_ => exact hhead
    | role => exact (hheads _ hatom).elim
    | eq => exact (hheads _ hatom).elim

  · intro assignment hbody
    let pulled := Function.update assignment source (redirect (assignment source))
    have hpulledSource : pulled source = redirect (assignment source) := by
      simp [pulled]
    have hpulledTarget : pulled target = assignment target := by
      simp [pulled, Ne.symm hne]
    have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom pulled atom := by
      intro atom hatom
      rcases hbodyShape atom hatom with hselected | hconcept
      · subst atom
        simpa [State.holdsAtom, hpulledSource, hpulledTarget] using
          hdirect role source target hrole (assignment source) (assignment target)
            (hbody (.role role source target) hatom)
      · cases atom with
        | concept literal node =>
            simp only [ConceptBodyAtom] at hconcept
            rcases literal with ⟨concept, negated⟩
            change negated = false at hconcept
            subst negated
            let literal : Lit Concept := .pos concept
            by_cases hnode : node = source
            · subst node
              simpa [State.holdsAtom, State.CoverHoldsAtom, hpulledSource] using
                hlocal.1 (assignment source) literal |>.mp
                  (hbody (.concept literal source) hatom)
            · have hpulled : pulled node = assignment node := by
                simp [pulled, hnode]
              simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using
                hbody (.concept literal node) hatom
        | role => contradiction
        | exists_ => contradiction
        | eq => contradiction
    rcases hdischarges pulled hrawBody with ⟨atom, hatom, hhead⟩
    refine ⟨atom, hatom, ?_⟩
    cases atom with
    | concept literal node =>
        by_cases hnode : node = source
        · subst node
          have hraw : state.label (redirect (assignment source)) literal := by
            simpa [State.holdsAtom, hpulledSource] using hhead
          exact (hlocal.1 (assignment source) literal).mpr hraw
        · have hpulled : pulled node = assignment node := by simp [pulled, hnode]
          simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using hhead
    | exists_ headRole filler node =>
        by_cases hnode : node = source
        · subst node
          have hraw : state.obligation headRole filler
              (redirect (assignment source)) := by
            simpa [State.holdsAtom, hpulledSource] using hhead
          exact (hlocal.2 (assignment source) headRole filler).mpr hraw
        · have hpulled : pulled node = assignment node := by simp [pulled, hnode]
          simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using hhead
    | role => exact (hheads _ hatom).elim
    | eq => exact (hheads _ hatom).elim

/-- Pull an arbitrary cover grounding through the redirect at every variable.
Local facts transfer concept and existential atoms, `RedirectCoverFacts`
transfers role atoms, and equality is preserved by congruence. Path-liftable
raw heads then transfer back to the original finite assignment. -/
theorem State.coverDischarges_of_redirectCoverFacts
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role)
    (hlocal : state.RedirectLocalFacts redirect)
    (hcover : state.RedirectCoverFacts redirect cover)
    (hheads : ∀ atom ∈ clause.head, PathLiftableHead atom)
    (hdischarges : state.Discharges clause) :
    state.CoverDischarges cover clause := by
  intro assignment hbody
  let pulled := fun v => redirect (assignment v)
  have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom pulled atom := by
    intro atom hatom
    have hholds := hbody atom hatom
    cases atom with
    | concept literal node =>
        exact (hlocal.1 (assignment node) literal).mp hholds
    | role role source target =>
        exact hcover role (assignment source) (assignment target) hholds
    | exists_ role filler node =>
        exact (hlocal.2 (assignment node) role filler).mp hholds
    | eq left right =>
        exact congrArg redirect hholds
  rcases hdischarges pulled hrawBody with ⟨atom, hatom, hholds⟩
  refine ⟨atom, hatom, ?_⟩
  cases atom with
  | concept literal node =>
      exact (hlocal.1 (assignment node) literal).mpr hholds
  | role => exact (hheads _ hatom).elim
  | exists_ role filler node =>
      exact (hlocal.2 (assignment node) role filler).mpr hholds
  | eq => exact (hheads _ hatom).elim

/-! ## Finite progress of rejected blocker learning -/

/-- At one fixed node budget, production cannot reject blocked-open candidates
forever when each rejection blacklists at least one previously available fold.
This is the termination measure implemented by Rust's equality-free certified
producer: fold pairs range over the finite node universe and the forbidden set
grows strictly after every rejected candidate. -/
theorem no_infinite_fresh_fold_rejections
    [Fintype Node] [DecidableEq Node]
    (forbidden learned : Nat → Finset (Node × Node))
    (hstep : ∀ round,
      forbidden (round + 1) = forbidden round ∪ learned round)
    (hfresh : ∀ round, ∃ fold ∈ learned round, fold ∉ forbidden round) : False := by
  have hstrict : ∀ round, forbidden round ⊂ forbidden (round + 1) := by
    intro round
    refine Finset.ssubset_iff_subset_ne.mpr ⟨?_, ?_⟩
    · rw [hstep]
      exact Finset.subset_union_left
    · obtain ⟨fold, hlearned, hnew⟩ := hfresh round
      intro heq
      have hnext : fold ∈ forbidden (round + 1) := by
        rw [hstep]
        exact Finset.mem_union_right _ hlearned
      exact hnew (heq ▸ hnext)
  have hcard : ∀ round,
      (forbidden 0).card + round ≤ (forbidden round).card := by
    intro round
    induction round with
    | zero => simp
    | succ round ih =>
        have hlt := Finset.card_lt_card (hstrict round)
        omega
  have huniv := Finset.card_le_card
    (show forbidden (Fintype.card (Node × Node) + 1) ⊆ Finset.univ by
      exact Finset.subset_univ _)
  have hbound := hcard (Fintype.card (Node × Node) + 1)
  simp only [Finset.card_univ] at huniv
  omega

/-- One producer attempt at a fixed node budget either returns the checked
round result consumed by the outer doubling proof or rejects a finite set of
blocker folds. Rejection is an internal search refinement, never a verdict. -/
inductive FoldLearningOutcome (Node Result : Type) where
  | done (result : Result)
  | rejected (folds : Finset (Node × Node))

/-- Executable shape of one fixed-budget blocker retry loop. The next attempt
is a function of the current blacklist. A rejection must expose at least one
fold not already blacklisted; this is the local contract enforced by Rust
before it retries. -/
structure FreshFoldProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : Finset (Node × Node) → FoldLearningOutcome Node Result
  rejectionFresh : ∀ forbidden folds,
    attempt forbidden = .rejected folds →
      ∃ fold ∈ folds, fold ∉ forbidden

/-- Proof-carrying result of the Rust checker/blacklist branch at one fixed
budget. A rejected candidate stores its exact serialized fold set together
with the fact established by at least one successful `HashSet::insert`.
Consequently the fatal stale-fold branch is absent from this type. -/
inductive GuardedFoldAttempt (Node Result : Type)
    [DecidableEq Node] (forbidden : Finset (Node × Node)) : Type where
  | done (result : Result)
  | rejected (folds : Finset (Node × Node))
      (fresh : ∃ fold ∈ folds, fold ∉ forbidden)

def GuardedFoldAttempt.erase
    [DecidableEq Node]
    {forbidden : Finset (Node × Node)} :
    GuardedFoldAttempt Node Result forbidden → FoldLearningOutcome Node Result
  | .done result => .done result
  | .rejected folds _ => .rejected folds

/-- Rust-mirrored fixed-budget producer. Its attempt is indexed by the actual
blacklist supplied to the search, and rejection can only be constructed from
a candidate carrying a newly inserted blocker pair. -/
structure GuardedFoldProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : ∀ forbidden : Finset (Node × Node),
    GuardedFoldAttempt Node Result forbidden

def GuardedFoldProducer.toFreshFoldProducer
    [DecidableEq Node]
    (producer : GuardedFoldProducer Node Result) :
    FreshFoldProducer Node Result where
  attempt forbidden := (producer.attempt forbidden).erase
  rejectionFresh := by
    intro forbidden folds hrejected
    cases hattempt : producer.attempt forbidden with
    | done result => simp [GuardedFoldAttempt.erase, hattempt] at hrejected
    | rejected learned fresh =>
        simp [GuardedFoldAttempt.erase, hattempt] at hrejected
        subst learned
        exact fresh

theorem GuardedFoldProducer.rejected_has_fresh
    [DecidableEq Node]
    (producer : GuardedFoldProducer Node Result)
    {forbidden folds : Finset (Node × Node)}
    (hrejected : (producer.attempt forbidden).erase = .rejected folds) :
    ∃ fold ∈ folds, fold ∉ forbidden := by
  exact producer.toFreshFoldProducer.rejectionFresh forbidden folds hrejected

def FreshFoldProducer.forbidden
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) : Nat → Finset (Node × Node)
  | 0 => ∅
  | round + 1 =>
      let current := producer.forbidden round
      match producer.attempt current with
      | .done _ => current
      | .rejected folds => current ∪ folds

def FreshFoldProducer.run
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) (round : Nat) :
    FoldLearningOutcome Node Result :=
  producer.attempt (producer.forbidden round)

theorem FreshFoldProducer.rejected_step
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    {round : Nat} {folds : Finset (Node × Node)}
    (hrun : producer.run round = .rejected folds) :
    producer.forbidden (round + 1) = producer.forbidden round ∪ folds ∧
      ∃ fold ∈ folds, fold ∉ producer.forbidden round := by
  have hattempt : producer.attempt (producer.forbidden round) = .rejected folds := hrun
  constructor
  · simp only [FreshFoldProducer.forbidden]
    rw [hattempt]
  · exact producer.rejectionFresh _ _ hattempt

/-- A conforming producer cannot reject a candidate whose complete fold report
is already contained in the blacklist. This is the exact progress guard used
by the executable retry loop: rejection is permitted only when it teaches the
next attempt at least one new blocker pair. -/
theorem FreshFoldProducer.rejected_not_subset
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    {forbidden folds : Finset (Node × Node)}
    (hrejected : producer.attempt forbidden = .rejected folds) :
    ¬ folds ⊆ forbidden := by
  obtain ⟨fold, hfold, hfresh⟩ := producer.rejectionFresh forbidden folds hrejected
  exact fun hsubset => hfresh (hsubset hfold)

/-- In particular, the modeled production retry can never reach Rust's fatal
"fold-free candidate rejected" branch. Such an outcome carries no fresh fold
and therefore contradicts the producer contract. -/
theorem FreshFoldProducer.not_rejected_empty
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    (forbidden : Finset (Node × Node)) :
    producer.attempt forbidden ≠ .rejected ∅ := by
  intro hrejected
  exact producer.rejected_not_subset hrejected (Finset.empty_subset _)

/-- The concrete retry layer terminates at every fixed node budget. This turns
the Rust producer's learned-fold loop into a total constructor of the checked
round outcome expected by the existing doubling theorem. -/
theorem fold_learning_eventually_done
    [Fintype Node] [DecidableEq Node]
    (run : Nat → FoldLearningOutcome Node Result)
    (forbidden : Nat → Finset (Node × Node))
    (hlearn : ∀ round folds, run round = .rejected folds →
      forbidden (round + 1) = forbidden round ∪ folds ∧
        ∃ fold ∈ folds, fold ∉ forbidden round) :
    ∃ round result, run round = .done result := by
  by_contra hdone
  have hrejected : ∀ round, ∃ folds, run round = .rejected folds := by
    intro round
    cases houtcome : run round with
    | done result =>
        exact False.elim (hdone ⟨round, result, houtcome⟩)
    | rejected folds => exact ⟨folds, rfl⟩
  choose learned hruns using hrejected
  apply no_infinite_fresh_fold_rejections forbidden learned
  · intro round
    exact (hlearn round (learned round) (hruns round)).1
  · intro round
    exact (hlearn round (learned round) (hruns round)).2

theorem FreshFoldProducer.eventually_done
    [Fintype Node] [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) :
    ∃ round result, producer.run round = .done result := by
  exact fold_learning_eventually_done producer.run producer.forbidden
    (fun _ _ hrun => producer.rejected_step hrun)

/-! ## Complete-fold-assignment refinement

Rejecting a redirected cover refutes the complete simultaneous fold assignment
used to construct that cover.  It does not refute any constituent fold in
isolation.  The following control model therefore learns exact assignments,
while permitting every pair to occur in a different assignment. -/

abbrev FoldAssignment (Node : Type) := Finset (Node × Node)

inductive FoldAssignmentOutcome (Node Result : Type) where
  | done (result : Result)
  | rejected (assignment : FoldAssignment Node)

/-- Fixed-budget production indexed by exact rejected assignments.  A retry
may reject only an assignment that has not already been rejected. -/
structure FoldAssignmentProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : Finset (FoldAssignment Node) → FoldAssignmentOutcome Node Result
  rejectionFresh : ∀ rejected assignment,
    attempt rejected = .rejected assignment → assignment ∉ rejected

def FoldAssignmentProducer.rejected
    [DecidableEq Node]
    (producer : FoldAssignmentProducer Node Result) :
    Nat → Finset (FoldAssignment Node)
  | 0 => ∅
  | round + 1 =>
      let current := producer.rejected round
      match producer.attempt current with
      | .done _ => current
      | .rejected assignment => insert assignment current

def FoldAssignmentProducer.run
    [DecidableEq Node]
    (producer : FoldAssignmentProducer Node Result) (round : Nat) :
    FoldAssignmentOutcome Node Result :=
  producer.attempt (producer.rejected round)

theorem FoldAssignmentProducer.rejected_step
    [DecidableEq Node]
    (producer : FoldAssignmentProducer Node Result)
    {round : Nat} {assignment : FoldAssignment Node}
    (hrun : producer.run round = .rejected assignment) :
    producer.rejected (round + 1) =
        insert assignment (producer.rejected round) ∧
      assignment ∉ producer.rejected round := by
  have hattempt : producer.attempt (producer.rejected round) =
      .rejected assignment := hrun
  constructor
  · simp only [FoldAssignmentProducer.rejected]
    rw [hattempt]
  · exact producer.rejectionFresh _ _ hattempt

/-- Exact-assignment learning terminates at a fixed finite node budget.  Its
finite search space is the powerset of finite blocker pairs, rather than the
pair set itself. -/
theorem FoldAssignmentProducer.eventually_done
    [Fintype Node] [DecidableEq Node]
    (producer : FoldAssignmentProducer Node Result) :
    ∃ round result, producer.run round = .done result := by
  by_contra hdone
  have hrejected : ∀ round, ∃ assignment,
      producer.run round = .rejected assignment := by
    intro round
    cases houtcome : producer.run round with
    | done result => exact False.elim (hdone ⟨round, result, houtcome⟩)
    | rejected assignment => exact ⟨assignment, rfl⟩
  choose assignment hruns using hrejected
  have hstrict : ∀ round,
      producer.rejected round ⊂ producer.rejected (round + 1) := by
    intro round
    have hstep := producer.rejected_step (hruns round)
    rw [hstep.1]
    exact Finset.ssubset_insert hstep.2
  have hcard : ∀ round,
      (producer.rejected 0).card + round ≤ (producer.rejected round).card := by
    intro round
    induction round with
    | zero => simp
    | succ round ih =>
        have hlt := Finset.card_lt_card (hstrict round)
        omega
  have huniv := Finset.card_le_card
    (show producer.rejected
        (Fintype.card (FoldAssignment Node) + 1) ⊆ Finset.univ by
      exact Finset.subset_univ _)
  have hbound := hcard (Fintype.card (FoldAssignment Node) + 1)
  simp only [Finset.card_univ] at huniv
  omega

/-- Constructor-guarded form of one complete-assignment attempt.  Production
code can report rejection only together with evidence that the exact
simultaneous assignment has not already been rejected. -/
inductive GuardedFoldAssignmentAttempt (Node Result : Type)
    [DecidableEq Node] (rejected : Finset (FoldAssignment Node)) where
  | done (result : Result)
  | rejected (assignment : FoldAssignment Node)
      (fresh : assignment ∉ rejected)

def GuardedFoldAssignmentAttempt.erase
    [DecidableEq Node]
    {rejected : Finset (FoldAssignment Node)}
    (attempt : GuardedFoldAssignmentAttempt Node Result rejected) :
    FoldAssignmentOutcome Node Result :=
  match attempt with
  | .done result => .done result
  | .rejected assignment _ => .rejected assignment

/-- A production assignment producer exposes only guarded attempts.  Erasing
the guard yields the finite producer consumed by the termination theorem. -/
structure GuardedFoldAssignmentProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : ∀ rejected : Finset (FoldAssignment Node),
    GuardedFoldAssignmentAttempt Node Result rejected

def GuardedFoldAssignmentProducer.toFoldAssignmentProducer
    [DecidableEq Node]
    (producer : GuardedFoldAssignmentProducer Node Result) :
    FoldAssignmentProducer Node Result where
  attempt rejected := (producer.attempt rejected).erase
  rejectionFresh rejected assignment hattempt := by
    change (producer.attempt rejected).erase =
      .rejected assignment at hattempt
    cases hguarded : producer.attempt rejected with
    | done result =>
        rw [hguarded] at hattempt
        simp [GuardedFoldAssignmentAttempt.erase] at hattempt
    | rejected candidate fresh =>
        rw [hguarded] at hattempt
        simp only [GuardedFoldAssignmentAttempt.erase] at hattempt
        cases hattempt
        exact fresh

theorem GuardedFoldAssignmentProducer.eventually_done
    [Fintype Node] [DecidableEq Node]
    (producer : GuardedFoldAssignmentProducer Node Result) :
    ∃ round result,
      producer.toFoldAssignmentProducer.run round = .done result :=
  producer.toFoldAssignmentProducer.eventually_done

/-! ## Cartesian assignment exhaustion and forced expansion -/

/-- The exact source-major Cartesian blocker enumeration used by Rust.  Each
result chooses one blocker for every listed blocked source. -/
def enumerateFoldAssignments [DecidableEq Node] :
    List (Node × List Node) → List (FoldAssignment Node)
  | [] => [∅]
  | (source, blockers) :: rest =>
      blockers.flatMap fun blocker =>
        (enumerateFoldAssignments rest).map
          (fun assignment => insert (source, blocker) assignment)

theorem enumerateFoldAssignments_nonempty
    [DecidableEq Node]
    {options : List (Node × List Node)}
    (hall : ∀ option ∈ options, option.2 ≠ []) :
    enumerateFoldAssignments options ≠ [] := by
  induction options with
  | nil => simp [enumerateFoldAssignments]
  | cons option rest ih =>
      rcases option with ⟨source, blockers⟩
      have hblockers : blockers ≠ [] := hall (source, blockers) (by simp)
      have hrest : ∀ option ∈ rest, option.2 ≠ [] := by
        intro option hoption
        exact hall option (by simp [hoption])
      cases hblockersList : blockers with
      | nil => exact (hblockers hblockersList).elim
      | cons blocker more =>
          have hassignments := ih hrest
          cases htail : enumerateFoldAssignments rest with
          | nil => exact (hassignments htail).elim
          | cons assignment assignments =>
              simp [enumerateFoldAssignments, htail]

/-- Every candidate pair occurs in at least one complete Cartesian assignment,
provided every other blocked source also has a blocker choice. -/
theorem pair_mem_enumerateFoldAssignments
    [DecidableEq Node]
    {options : List (Node × List Node)}
    (hall : ∀ option ∈ options, option.2 ≠ [])
    {source blocker blockers}
    (hoption : (source, blockers) ∈ options)
    (hblocker : blocker ∈ blockers) :
    ∃ assignment ∈ enumerateFoldAssignments options,
      (source, blocker) ∈ assignment := by
  induction options with
  | nil => simp at hoption
  | cons option rest ih =>
      rcases option with ⟨firstSource, firstBlockers⟩
      simp only [List.mem_cons] at hoption
      rcases hoption with hfirst | hrest
      · cases hfirst
        have htail : ∀ option ∈ rest, option.2 ≠ [] := by
          intro option hoption
          exact hall option (by simp [hoption])
        have hnonempty := enumerateFoldAssignments_nonempty htail
        cases hassignments : enumerateFoldAssignments rest with
        | nil => exact (hnonempty hassignments).elim
        | cons assignment assignments =>
            refine ⟨insert (source, blocker) assignment, ?_, Finset.mem_insert_self ..⟩
            simp only [enumerateFoldAssignments, List.mem_flatMap, List.mem_map]
            refine ⟨blocker, hblocker, assignment, ?_, rfl⟩
            rw [hassignments]
            simp
      · have hfirstNonempty : firstBlockers ≠ [] :=
          hall (firstSource, firstBlockers) (by simp)
        have htail : ∀ option ∈ rest, option.2 ≠ [] := by
          intro option hoption
          exact hall option (by simp [hoption])
        cases hfirstBlockers : firstBlockers with
        | nil => exact (hfirstNonempty hfirstBlockers).elim
        | cons firstBlocker more =>
            rcases ih htail hrest with
              ⟨assignment, hassignment, hpair⟩
            refine ⟨insert (firstSource, firstBlocker) assignment, ?_, ?_⟩
            · simp only [enumerateFoldAssignments, List.mem_flatMap, List.mem_map]
              refine ⟨firstBlocker, ?_, assignment, hassignment, rfl⟩
              simp
            · exact Finset.mem_insert_of_mem hpair

/-- Pair-level expansion control is the union of already rejected complete
assignments.  Membership records provenance in one exact rejected assignment;
it does not assert that the pair is independently invalid. -/
def rejectedAssignmentPairs [DecidableEq Node]
    (rejected : Finset (FoldAssignment Node)) : FoldAssignment Node :=
  rejected.biUnion id

/-- The exact pair set learned by Rust after exhausting the complete product
for one blocker-option list. -/
def foldOptionPairs [DecidableEq Node]
    (options : List (Node × List Node)) : FoldAssignment Node :=
  match options with
  | [] => ∅
  | option :: rest =>
      option.2.toFinset.image (fun blocker => (option.1, blocker)) ∪
        foldOptionPairs rest

theorem mem_foldOptionPairs_iff
    [DecidableEq Node]
    {options : List (Node × List Node)} {source blocker : Node} :
    (source, blocker) ∈ foldOptionPairs options ↔
      ∃ blockers, (source, blockers) ∈ options ∧ blocker ∈ blockers := by
  induction options with
  | nil => simp [foldOptionPairs]
  | cons option options ih =>
      rcases option with ⟨firstSource, firstBlockers⟩
      simp only [foldOptionPairs, Finset.mem_union, Finset.mem_image,
        List.mem_cons, Prod.mk.injEq, List.mem_toFinset, ih]
      constructor
      · rintro (⟨candidate, hcandidate, heq⟩ |
          ⟨blockers, hoption, hblocker⟩)
        · rcases heq with ⟨rfl, rfl⟩
          exact ⟨firstBlockers, Or.inl ⟨rfl, rfl⟩, hcandidate⟩
        · exact ⟨blockers, Or.inr hoption, hblocker⟩
      · rintro ⟨blockers, hoption | hoption, hblocker⟩
        · rcases hoption with ⟨rfl, rfl⟩
          exact Or.inl ⟨blocker, hblocker, ⟨rfl, rfl⟩⟩
        · exact Or.inr ⟨blockers, hoption, hblocker⟩

theorem pair_mem_rejectedAssignmentPairs
    [DecidableEq Node]
    {rejected : Finset (FoldAssignment Node)} {pair : Node × Node} :
    pair ∈ rejectedAssignmentPairs rejected ↔
      ∃ assignment ∈ rejected, pair ∈ assignment := by
  simp [rejectedAssignmentPairs]

/-- Once every complete Cartesian assignment has been checker-rejected, every
available source/blocker pair is present in expansion control.  This is the
formal justification for Rust forcing those sources to expand only after the
local assignment product has been exhausted. -/
theorem pair_mem_rejected_of_assignment_exhaustion
    [DecidableEq Node]
    {options : List (Node × List Node)}
    (hall : ∀ option ∈ options, option.2 ≠ [])
    (rejected : Finset (FoldAssignment Node))
    (hexhausted : ∀ assignment ∈ enumerateFoldAssignments options,
      assignment ∈ rejected)
    {source blocker blockers}
    (hoption : (source, blockers) ∈ options)
    (hblocker : blocker ∈ blockers) :
    (source, blocker) ∈ rejectedAssignmentPairs rejected := by
  rcases pair_mem_enumerateFoldAssignments hall hoption hblocker with
    ⟨assignment, hassignment, hpair⟩
  exact pair_mem_rejectedAssignmentPairs.mpr
    ⟨assignment, hexhausted assignment hassignment, hpair⟩

def SourceExpansionControlled [DecidableEq Node]
    (rejected : Finset (FoldAssignment Node))
    (source : Node) (blockers : List Node) : Prop :=
  ∀ blocker ∈ blockers,
    (source, blocker) ∈ rejectedAssignmentPairs rejected

theorem sourceExpansionControlled_of_assignment_exhaustion
    [DecidableEq Node]
    {options : List (Node × List Node)}
    (hall : ∀ option ∈ options, option.2 ≠ [])
    (rejected : Finset (FoldAssignment Node))
    (hexhausted : ∀ assignment ∈ enumerateFoldAssignments options,
      assignment ∈ rejected)
    {source blockers}
    (hoption : (source, blockers) ∈ options) :
    SourceExpansionControlled rejected source blockers := by
  intro blocker hblocker
  exact pair_mem_rejected_of_assignment_exhaustion hall rejected hexhausted
    hoption hblocker

/-- One production attempt indexed by the blocker options reconstructed for
the current rerun. A rejection must be both fresh and an element of that exact
Cartesian product. -/
inductive CartesianFoldAssignmentAttempt (Node Result : Type)
    [DecidableEq Node]
    (options : List (Node × List Node))
    (rejected : Finset (FoldAssignment Node)) where
  | done (result : Result)
  | rejected (assignment : FoldAssignment Node)
      (generated : assignment ∈ enumerateFoldAssignments options)
      (fresh : assignment ∉ rejected)

def CartesianFoldAssignmentAttempt.toGuarded
    [DecidableEq Node]
    {options : List (Node × List Node)}
    {rejected : Finset (FoldAssignment Node)}
    (attempt : CartesianFoldAssignmentAttempt Node Result options rejected) :
    GuardedFoldAssignmentAttempt Node Result rejected :=
  match attempt with
  | .done result => .done result
  | .rejected assignment _ fresh => .rejected assignment fresh

/-- Production control with blocker options allowed to change after every
rejected candidate and ensuing rerun, exactly as in Rust. -/
structure CartesianFoldAssignmentProducer (Node Result : Type)
    [DecidableEq Node] where
  options : Finset (FoldAssignment Node) → List (Node × List Node)
  optionNonempty : ∀ rejected option,
    option ∈ options rejected → option.2 ≠ []
  attempt : ∀ rejected : Finset (FoldAssignment Node),
    CartesianFoldAssignmentAttempt Node Result (options rejected) rejected

def CartesianFoldAssignmentProducer.toGuarded
    [DecidableEq Node]
    (producer : CartesianFoldAssignmentProducer Node Result) :
    GuardedFoldAssignmentProducer Node Result where
  attempt rejected := (producer.attempt rejected).toGuarded

theorem CartesianFoldAssignmentProducer.rejection_generated
    [DecidableEq Node]
    (producer : CartesianFoldAssignmentProducer Node Result)
    {rejected : Finset (FoldAssignment Node)}
    {assignment : FoldAssignment Node}
    {generated : assignment ∈
      enumerateFoldAssignments (producer.options rejected)}
    {fresh : assignment ∉ rejected}
    (_hattempt : producer.attempt rejected =
      .rejected assignment generated fresh) :
    assignment ∈ enumerateFoldAssignments (producer.options rejected) :=
  generated

theorem CartesianFoldAssignmentProducer.eventually_done
    [Fintype Node] [DecidableEq Node]
    (producer : CartesianFoldAssignmentProducer Node Result) :
    ∃ round result,
      producer.toGuarded.toFoldAssignmentProducer.run round = .done result :=
  producer.toGuarded.eventually_done

/-! ## Executable Cartesian producer

Rust selects the first source-major Cartesian assignment absent from its
rejected set.  These definitions expose that exact computation, rather than
requiring callers to manufacture a proof-indexed producer directly. -/

def firstFreshFoldAssignment [DecidableEq Node]
    (rejected : Finset (FoldAssignment Node)) :
    List (FoldAssignment Node) → Option (FoldAssignment Node)
  | [] => none
  | assignment :: assignments =>
      if assignment ∈ rejected then
        firstFreshFoldAssignment rejected assignments
      else
        some assignment

theorem firstFreshFoldAssignment_eq_some_mem
    [DecidableEq Node]
    {rejected : Finset (FoldAssignment Node)}
    {assignments : List (FoldAssignment Node)}
    {assignment : FoldAssignment Node}
    (hselect : firstFreshFoldAssignment rejected assignments = some assignment) :
    assignment ∈ assignments := by
  induction assignments with
  | nil => simp [firstFreshFoldAssignment] at hselect
  | cons candidate assignments ih =>
      by_cases hrejected : candidate ∈ rejected
      · simp only [firstFreshFoldAssignment, if_pos hrejected] at hselect
        exact List.mem_cons_of_mem candidate (ih hselect)
      · simp only [firstFreshFoldAssignment, if_neg hrejected,
          Option.some.injEq] at hselect
        subst assignment
        exact List.mem_cons_self

theorem firstFreshFoldAssignment_eq_some_fresh
    [DecidableEq Node]
    {rejected : Finset (FoldAssignment Node)}
    {assignments : List (FoldAssignment Node)}
    {assignment : FoldAssignment Node}
    (hselect : firstFreshFoldAssignment rejected assignments = some assignment) :
    assignment ∉ rejected := by
  induction assignments with
  | nil => simp [firstFreshFoldAssignment] at hselect
  | cons candidate assignments ih =>
      by_cases hrejected : candidate ∈ rejected
      · simp only [firstFreshFoldAssignment, if_pos hrejected] at hselect
        exact ih hselect
      · simp only [firstFreshFoldAssignment, if_neg hrejected,
          Option.some.injEq] at hselect
        rwa [← hselect]

theorem firstFreshFoldAssignment_eq_none_iff
    [DecidableEq Node]
    (rejected : Finset (FoldAssignment Node))
    (assignments : List (FoldAssignment Node)) :
    firstFreshFoldAssignment rejected assignments = none ↔
      ∀ assignment ∈ assignments, assignment ∈ rejected := by
  induction assignments with
  | nil => simp [firstFreshFoldAssignment]
  | cons candidate assignments ih =>
      by_cases hrejected : candidate ∈ rejected
      · simp only [firstFreshFoldAssignment, if_pos hrejected, ih,
          List.mem_cons, forall_eq_or_imp]
        constructor
        · intro hall
          exact ⟨hrejected, hall⟩
        · intro hall
          exact hall.2
      · simp [firstFreshFoldAssignment, hrejected]

/-- Construct the proof-indexed producer from KM's executable control shape.
The checker either accepts the selected candidate and returns a result or
rejects exactly that candidate.  Exhaustion invokes the fold-free/forced-
expansion continuation. -/
def CartesianFoldAssignmentProducer.ofRuntime
    [DecidableEq Node]
    (options : Finset (FoldAssignment Node) → List (Node × List Node))
    (optionNonempty : ∀ rejected option,
      option ∈ options rejected → option.2 ≠ [])
    (check : Finset (FoldAssignment Node) → FoldAssignment Node →
      Result ⊕ Unit)
    (onExhausted : Finset (FoldAssignment Node) → Result) :
    CartesianFoldAssignmentProducer Node Result where
  options := options
  optionNonempty := optionNonempty
  attempt rejected :=
    match hselect : firstFreshFoldAssignment rejected
        (enumerateFoldAssignments (options rejected)) with
    | none => CartesianFoldAssignmentAttempt.done (onExhausted rejected)
    | some assignment =>
        match check rejected assignment with
        | .inl result => CartesianFoldAssignmentAttempt.done result
        | .inr _ => CartesianFoldAssignmentAttempt.rejected assignment
            (firstFreshFoldAssignment_eq_some_mem hselect)
            (firstFreshFoldAssignment_eq_some_fresh hselect)

/-- Data supplied by KM's fixed-budget retry loop. Unlike the dependent
producer interface, these are ordinary executable functions: blocker-option
reconstruction, candidate checking, and the continuation used after exact
Cartesian exhaustion. -/
structure CartesianFoldAssignmentRuntime (Node Result : Type)
    [DecidableEq Node] where
  options : Finset (FoldAssignment Node) → List (Node × List Node)
  optionNonempty : ∀ rejected option,
    option ∈ options rejected → option.2 ≠ []
  check : Finset (FoldAssignment Node) → FoldAssignment Node → Result ⊕ Unit
  onExhausted : Finset (FoldAssignment Node) → Result

/-! ### Runtime options derived from a total fold table -/

noncomputable def foldBlockers [Fintype Node] [DecidableEq Node]
    (fold : Node → Node → Prop) [DecidableRel fold] (source : Node) : List Node :=
  (Finset.univ.filter (fold source)).toList

theorem mem_foldBlockers_iff
    [Fintype Node] [DecidableEq Node]
    (fold : Node → Node → Prop) [DecidableRel fold]
    (source blocker : Node) :
    blocker ∈ foldBlockers fold source ↔ fold source blocker := by
  simp [foldBlockers]

noncomputable def foldOptions [Fintype Node] [DecidableEq Node]
    (fold : Node → Node → Prop) [DecidableRel fold]
    (sources : List Node) : List (Node × List Node) :=
  sources.map fun source => (source, foldBlockers fold source)

theorem foldOptions_option_nonempty
    [Fintype Node] [DecidableEq Node]
    (blocked : Node → Bool)
    (fold : Node → Node → Prop) [DecidableRel fold]
    (hfoldTotal : State.BlockedFoldTotal blocked fold)
    (sources : List Node)
    (hsources : ∀ source ∈ sources, blocked source = true)
    (option : Node × List Node)
    (hoption : option ∈ foldOptions fold sources) :
    option.2 ≠ [] := by
  rcases List.mem_map.mp hoption with ⟨source, hsource, rfl⟩
  obtain ⟨blocker, hfold⟩ := hfoldTotal source (hsources source hsource)
  intro hempty
  have hmem : blocker ∈ foldBlockers fold source :=
    (mem_foldBlockers_iff fold source blocker).mpr hfold
  change foldBlockers fold source = [] at hempty
  rw [hempty] at hmem
  simp at hmem

/-- Build the executable inner producer from the blocked sources and total
fold relation exposed by a concrete runtime terminal. -/
noncomputable def CartesianFoldAssignmentRuntime.ofFoldTable
    [Fintype Node] [DecidableEq Node]
    (blocked : Finset (FoldAssignment Node) → Node → Bool)
    (fold : Finset (FoldAssignment Node) → Node → Node → Prop)
    (foldDecidable : ∀ rejected, DecidableRel (fold rejected))
    (hfoldTotal : ∀ rejected,
      State.BlockedFoldTotal (blocked rejected) (fold rejected))
    (sources : Finset (FoldAssignment Node) → List Node)
    (hsources : ∀ rejected source, source ∈ sources rejected →
      blocked rejected source = true)
    (check : Finset (FoldAssignment Node) → FoldAssignment Node →
      Result ⊕ Unit)
    (onExhausted : Finset (FoldAssignment Node) → Result) :
    CartesianFoldAssignmentRuntime Node Result where
  options rejected :=
    letI := foldDecidable rejected
    foldOptions (fold rejected) (sources rejected)
  optionNonempty rejected option hoption := by
    letI := foldDecidable rejected
    exact foldOptions_option_nonempty (blocked rejected) (fold rejected)
      (hfoldTotal rejected) (sources rejected) (hsources rejected) option hoption
  check := check
  onExhausted := onExhausted

def CartesianFoldAssignmentRuntime.toProducer
    [DecidableEq Node]
    (runtime : CartesianFoldAssignmentRuntime Node Result) :
    CartesianFoldAssignmentProducer Node Result :=
  CartesianFoldAssignmentProducer.ofRuntime runtime.options
    runtime.optionNonempty runtime.check runtime.onExhausted

theorem CartesianFoldAssignmentRuntime.eventually_done
    [Fintype Node] [DecidableEq Node]
    (runtime : CartesianFoldAssignmentRuntime Node Result) :
    ∃ round result,
      runtime.toProducer.toGuarded.toFoldAssignmentProducer.run round =
        .done result :=
  runtime.toProducer.eventually_done

theorem CartesianFoldAssignmentProducer.ofRuntime_exhausted
    [DecidableEq Node]
    (options : Finset (FoldAssignment Node) → List (Node × List Node))
    (optionNonempty : ∀ rejected option,
      option ∈ options rejected → option.2 ≠ [])
    (check : Finset (FoldAssignment Node) → FoldAssignment Node →
      Result ⊕ Unit)
    (onExhausted : Finset (FoldAssignment Node) → Result)
    {rejected : Finset (FoldAssignment Node)}
    (hselect : firstFreshFoldAssignment rejected
      (enumerateFoldAssignments (options rejected)) = none) :
    (CartesianFoldAssignmentProducer.ofRuntime options optionNonempty check
      onExhausted).attempt rejected = .done (onExhausted rejected) := by
  change (match hselected : firstFreshFoldAssignment rejected
      (enumerateFoldAssignments (options rejected)) with
    | none => .done (onExhausted rejected)
    | some assignment =>
        match check rejected assignment with
        | .inl result => .done result
        | .inr _ => .rejected assignment
            (firstFreshFoldAssignment_eq_some_mem hselected)
            (firstFreshFoldAssignment_eq_some_fresh hselected)) =
      CartesianFoldAssignmentAttempt.done (onExhausted rejected)
  split
  · rfl
  · rename_i assignment hsome
    rw [hselect] at hsome
    contradiction

theorem CartesianFoldAssignmentProducer.ofRuntime_exhaustion_complete
    [DecidableEq Node]
    (options : Finset (FoldAssignment Node) → List (Node × List Node))
    (optionNonempty : ∀ rejected option,
      option ∈ options rejected → option.2 ≠ [])
    (check : Finset (FoldAssignment Node) → FoldAssignment Node →
      Result ⊕ Unit)
    (onExhausted : Finset (FoldAssignment Node) → Result)
    {rejected : Finset (FoldAssignment Node)}
    (hselect : firstFreshFoldAssignment rejected
      (enumerateFoldAssignments (options rejected)) = none) :
    (CartesianFoldAssignmentProducer.ofRuntime options optionNonempty check
        onExhausted).attempt rejected = .done (onExhausted rejected) ∧
      ∀ assignment ∈ enumerateFoldAssignments (options rejected),
        assignment ∈ rejected := by
  constructor
  · exact CartesianFoldAssignmentProducer.ofRuntime_exhausted options
      optionNonempty check onExhausted hselect
  · intro assignment hgenerated
    exact (firstFreshFoldAssignment_eq_none_iff rejected
      (enumerateFoldAssignments (options rejected))).mp hselect
      assignment hgenerated

/-- A blocker-aware runtime terminal and checked fold metadata supply every
regular-model invariant. In particular, saturation transfers by state equality
because the serializer no longer mutates the completion graph. -/
theorem FiniteRegularCertificate.check_of_blocked_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hcoverClosed : certificate.CoverClosed)
    (hcoverEdge : ∀ role source target,
      certificate.coverRelation role source target →
        certificate.state.edge role source target) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  exact certificate.check_of_producer_invariants hauthorized hguarded hheads
    hclash hwitness hcoverClosed hcoverEdge hsaturated

/-- Concrete producer theorem for the proved local residual fragment. Unlike
`check_of_blocked_runtime_terminal`, this theorem permits redirected cover
edges absent from the raw graph outside residual bodies. Local-fact invariance
and exact body-role cover containment pull every finite cover grounding back
to ordinary saturation. -/
theorem FiniteRegularCertificate.check_of_local_blocked_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hdirect : ∀ clause ∈ certificate.residual,
      certificate.state.DirectCoverForBody certificate.redirect
        certificate.coverRelation clause)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  have hcoverDischarges : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause := by
    intro clause hclause
    exact certificate.state.coverDischarges_of_singleDirectRoleBody
      certificate.redirect certificate.coverRelation clause
      (hshape clause hclause) hlocal (hdirect clause hclause)
      (hheads clause hclause)
      (hsaturated clause hclause)
  apply certificate.check_complete
  exact ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
    hcoverDischarges⟩

/-- Exact cover-aware producer boundary. A runtime search that has exhausted
residual obstructions in the redirected endpoint cover may publish a regular
model without imposing a syntactic restriction on residual bodies. This is
the semantic target for the cover-aware Rust terminal selector. -/
theorem FiniteRegularCertificate.check_of_cover_saturated_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hcoverClosed : certificate.CoverClosed)
    (hcoverSaturated : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  exact certificate.check_complete
    ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
      hcoverSaturated⟩

/-- General redirected-cover producer theorem. Redirecting both endpoints of
every cover edge back into the raw saturated graph removes the single-edge and
simple-role restrictions from residual bodies. -/
theorem FiniteRegularCertificate.check_of_redirect_cover_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hredirectCover : certificate.state.RedirectCoverFacts certificate.redirect
      certificate.coverRelation)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  have hcoverDischarges : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause := by
    intro clause hclause
    exact certificate.state.coverDischarges_of_redirectCoverFacts
      certificate.redirect certificate.coverRelation clause hlocal
      hredirectCover (hheads clause hclause) (hsaturated clause hclause)
  apply certificate.check_complete
  exact ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
    hcoverDischarges⟩

/-- For residual clauses whose body roles are syntactically simple, the
serialized endpoint cover itself supplies the direct-body premise. This is the
premise-free cover bridge for the complete local blocking fragment: no
producer-specific assertion about each redirected cover edge remains. -/
theorem FiniteRegularCertificate.check_of_simple_local_blocked_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hsimple : ∀ clause ∈ certificate.residual,
      clause.SimpleBodyRoles certificate.rules)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hgenerated : certificate.CoverGenerated)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  apply certificate.check_of_local_blocked_runtime_terminal runtime blocked fold
    hstate hterminal hwitnessRefines hredirectRefines hauthorized hguarded
    hshape hheads hlocal
  · intro clause hclause
    exact certificate.directCoverForBody_of_generated hgenerated clause
      (hsimple clause hclause)
  · exact hcoverClosed

/-- A saturated runtime terminal with no blocker folds is accepted using the
identity redirect. Fold-table totality forces every node to be unblocked, so
every existential obligation already has an ordinary runtime witness. This is
the checker-completeness argument for the final fold-free retry attempted by
the Rust producer. -/
theorem FiniteRegularCertificate.check_of_fold_free_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hfoldTotal : State.BlockedFoldTotal blocked fold)
    (hfoldFree : ∀ source blocker, ¬ fold source blocker)
    (hredirect : certificate.redirect = id)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hdirect : ∀ clause ∈ certificate.residual,
      certificate.state.DirectCoverForBody certificate.redirect
        certificate.coverRelation clause)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hunblocked : ∀ source, blocked source = false := by
    intro source
    cases hblocked : blocked source with
    | false => rfl
    | true =>
        obtain ⟨blocker, hfold⟩ := hfoldTotal source hblocked
        exact (hfoldFree source blocker hfold).elim
  have hwitnessRefines : runtime.BlockedWitnessRefines blocked fold := by
    intro source role filler hobligation hblocked
    simp [hunblocked source] at hblocked
  have hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect := by
    constructor
    · intro source _
      simp [hredirect]
    · intro source blocker hfold
      exact (hfoldFree source blocker hfold).elim
  have hlocal : certificate.state.RedirectLocalFacts certificate.redirect := by
    simp [State.RedirectLocalFacts, hredirect]
  exact certificate.check_of_local_blocked_runtime_terminal runtime blocked fold
    hstate hterminal hwitnessRefines hredirectRefines hauthorized hguarded hshape
    hheads hlocal hdirect hcoverClosed

#print axioms FiniteRegularCertificate.check_of_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_local_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_cover_saturated_runtime_terminal
#print axioms State.coverDischarges_of_redirectCoverFacts
#print axioms FiniteRegularCertificate.check_of_redirect_cover_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_simple_local_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_fold_free_runtime_terminal
#print axioms no_infinite_fresh_fold_rejections
#print axioms fold_learning_eventually_done
#print axioms FreshFoldProducer.rejected_step
#print axioms FreshFoldProducer.rejected_not_subset
#print axioms FreshFoldProducer.not_rejected_empty
#print axioms FreshFoldProducer.eventually_done
#print axioms GuardedFoldProducer.rejected_has_fresh
#print axioms FoldAssignmentProducer.rejected_step
#print axioms FoldAssignmentProducer.eventually_done
#print axioms GuardedFoldAssignmentProducer.eventually_done
#print axioms enumerateFoldAssignments_nonempty
#print axioms pair_mem_enumerateFoldAssignments
#print axioms pair_mem_rejected_of_assignment_exhaustion
#print axioms sourceExpansionControlled_of_assignment_exhaustion
#print axioms mem_foldOptionPairs_iff
#print axioms CartesianFoldAssignmentProducer.rejection_generated
#print axioms CartesianFoldAssignmentProducer.eventually_done
#print axioms firstFreshFoldAssignment_eq_some_mem
#print axioms firstFreshFoldAssignment_eq_some_fresh
#print axioms firstFreshFoldAssignment_eq_none_iff
#print axioms CartesianFoldAssignmentProducer.ofRuntime_exhausted
#print axioms CartesianFoldAssignmentProducer.ofRuntime_exhaustion_complete
#print axioms CartesianFoldAssignmentRuntime.eventually_done
#print axioms mem_foldBlockers_iff
#print axioms foldOptions_option_nonempty

end ContextCalculus.Hypertableau
