import ContextCalculus.HypertableauRuntimeSearch
import ContextCalculus.HypertableauRegularCertificate

/-!
# Equality-free blocked-open regular certificate production

This module composes the concrete blocker-aware terminal selector with the
regular certificate producer boundary. The finite certificate retains the raw
saturated terminal graph. Existential witnesses are read at blocker redirects,
so certificate production neither copies edges nor creates new clause matches.
-/

namespace ContextCalculus.Hypertableau

/-! ## A proved local residual-clause boundary -/

def ConceptBodyAtom : Atom Variable Concept Role → Prop
  | .concept literal _ => literal.neg = false
  | _ => False

/-- A residual body is local to one directed forest edge: it contains only
positive concept tests, or positive concept tests plus one repeated syntactic
role atom between two distinct variables. This is the first production shape
for which redirected-cover grounding can be pulled back constructively. -/
def Clause.SingleDirectRoleBody
    (clause : Clause Variable Concept Role) : Prop :=
  (∀ atom ∈ clause.body, ConceptBodyAtom atom) ∨
  ∃ role source target, source ≠ target ∧
    Atom.role role source target ∈ clause.body ∧
    ∀ atom ∈ clause.body,
      atom = .role role source target ∨ ConceptBodyAtom atom

def Clause.SimpleBodyRoles
    (rules : UnravellingRoleRules Role)
    (clause : Clause Variable Concept Role) : Prop :=
  ∀ role source target, Atom.role role source target ∈ clause.body →
    rules.SyntacticallySimple role

/-- For a syntactically simple body role, every endpoint-cover edge is one raw
edge at the redirected source. Role-rule conclusions require a separate
closure-local theorem and are intentionally excluded from this boundary. -/
def State.DirectCoverForBody
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role) : Prop :=
  ∀ role sourceVariable targetVariable,
    Atom.role role sourceVariable targetVariable ∈ clause.body →
    ∀ source target, cover role source target →
    state.edge role (redirect source) target

/-- Every endpoint-cover fact is represented by a raw completion edge after
redirecting both finite endpoints. This condition is independent of residual
clause shape and accommodates inverse and chain closure when the redirect is a
role bisimulation. -/
def State.RedirectCoverFacts
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop) : Prop :=
  ∀ role source target, cover role source target →
    state.edge role (redirect source) (redirect target)

/-- Every serialized cover edge was generated by the endpoint-role closure;
the checker separately proves the converse closure inclusion. -/
def FiniteRegularCertificate.CoverGenerated
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount) : Prop :=
  ∀ role source target, certificate.coverRelation role source target →
    EndpointRole certificate.state certificate.redirect certificate.rules
      role source target

theorem FiniteRegularCertificate.directCoverForBody_of_generated
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (hgenerated : certificate.CoverGenerated)
    (clause : Clause (Fin variableCount) (Fin conceptCount) (Fin roleCount))
    (hsimple : clause.SimpleBodyRoles certificate.rules) :
    certificate.state.DirectCoverForBody certificate.redirect
      certificate.coverRelation clause := by
  intro role sourceVariable targetVariable hrole source target hcover
  exact (hgenerated role source target hcover).raw_of_syntacticallySimple
    (hsimple role sourceVariable targetVariable hrole)

/-- Pull a cover grounding of one local residual clause back to the raw
saturated completion state, then transfer its concept or existential head to
the original endpoint assignment. -/
theorem State.coverDischarges_of_singleDirectRoleBody
    [DecidableEq Variable]
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role)
    (hshape : clause.SingleDirectRoleBody)
    (hlocal : state.RedirectLocalFacts redirect)
    (hdirect : state.DirectCoverForBody redirect cover clause)
    (hheads : ∀ atom ∈ clause.head, PathLiftableHead atom)
    (hdischarges : state.Discharges clause) :
    state.CoverDischarges cover clause := by
  classical
  rcases hshape with hconcepts | ⟨role, source, target, hne, hrole, hbodyShape⟩
  · intro assignment hbody
    have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom assignment atom := by
      intro atom hatom
      cases atom with
      | concept literal node =>
          exact hbody (.concept literal node) hatom
      | role => exact (hconcepts _ hatom).elim
      | exists_ => exact (hconcepts _ hatom).elim
      | eq => exact (hconcepts _ hatom).elim
    rcases hdischarges assignment hrawBody with ⟨atom, hatom, hhead⟩
    refine ⟨atom, hatom, ?_⟩
    cases atom with
    | concept => exact hhead
    | exists_ => exact hhead
    | role => exact (hheads _ hatom).elim
    | eq => exact (hheads _ hatom).elim

  · intro assignment hbody
    let pulled := Function.update assignment source (redirect (assignment source))
    have hpulledSource : pulled source = redirect (assignment source) := by
      simp [pulled]
    have hpulledTarget : pulled target = assignment target := by
      simp [pulled, Ne.symm hne]
    have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom pulled atom := by
      intro atom hatom
      rcases hbodyShape atom hatom with hselected | hconcept
      · subst atom
        simpa [State.holdsAtom, hpulledSource, hpulledTarget] using
          hdirect role source target hrole (assignment source) (assignment target)
            (hbody (.role role source target) hatom)
      · cases atom with
        | concept literal node =>
            simp only [ConceptBodyAtom] at hconcept
            rcases literal with ⟨concept, negated⟩
            change negated = false at hconcept
            subst negated
            let literal : Lit Concept := .pos concept
            by_cases hnode : node = source
            · subst node
              simpa [State.holdsAtom, State.CoverHoldsAtom, hpulledSource] using
                hlocal.1 (assignment source) literal |>.mp
                  (hbody (.concept literal source) hatom)
            · have hpulled : pulled node = assignment node := by
                simp [pulled, hnode]
              simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using
                hbody (.concept literal node) hatom
        | role => contradiction
        | exists_ => contradiction
        | eq => contradiction
    rcases hdischarges pulled hrawBody with ⟨atom, hatom, hhead⟩
    refine ⟨atom, hatom, ?_⟩
    cases atom with
    | concept literal node =>
        by_cases hnode : node = source
        · subst node
          have hraw : state.label (redirect (assignment source)) literal := by
            simpa [State.holdsAtom, hpulledSource] using hhead
          exact (hlocal.1 (assignment source) literal).mpr hraw
        · have hpulled : pulled node = assignment node := by simp [pulled, hnode]
          simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using hhead
    | exists_ headRole filler node =>
        by_cases hnode : node = source
        · subst node
          have hraw : state.obligation headRole filler
              (redirect (assignment source)) := by
            simpa [State.holdsAtom, hpulledSource] using hhead
          exact (hlocal.2 (assignment source) headRole filler).mpr hraw
        · have hpulled : pulled node = assignment node := by simp [pulled, hnode]
          simpa [State.holdsAtom, State.CoverHoldsAtom, hpulled] using hhead
    | role => exact (hheads _ hatom).elim
    | eq => exact (hheads _ hatom).elim

/-- Pull an arbitrary cover grounding through the redirect at every variable.
Local facts transfer concept and existential atoms, `RedirectCoverFacts`
transfers role atoms, and equality is preserved by congruence. Path-liftable
raw heads then transfer back to the original finite assignment. -/
theorem State.coverDischarges_of_redirectCoverFacts
    (state : State Node Concept Role) (redirect : Node → Node)
    (cover : Role → Node → Node → Prop)
    (clause : Clause Variable Concept Role)
    (hlocal : state.RedirectLocalFacts redirect)
    (hcover : state.RedirectCoverFacts redirect cover)
    (hheads : ∀ atom ∈ clause.head, PathLiftableHead atom)
    (hdischarges : state.Discharges clause) :
    state.CoverDischarges cover clause := by
  intro assignment hbody
  let pulled := fun v => redirect (assignment v)
  have hrawBody : ∀ atom ∈ clause.body, state.holdsAtom pulled atom := by
    intro atom hatom
    have hholds := hbody atom hatom
    cases atom with
    | concept literal node =>
        exact (hlocal.1 (assignment node) literal).mp hholds
    | role role source target =>
        exact hcover role (assignment source) (assignment target) hholds
    | exists_ role filler node =>
        exact (hlocal.2 (assignment node) role filler).mp hholds
    | eq left right =>
        exact congrArg redirect hholds
  rcases hdischarges pulled hrawBody with ⟨atom, hatom, hholds⟩
  refine ⟨atom, hatom, ?_⟩
  cases atom with
  | concept literal node =>
      exact (hlocal.1 (assignment node) literal).mpr hholds
  | role => exact (hheads _ hatom).elim
  | exists_ role filler node =>
      exact (hlocal.2 (assignment node) role filler).mpr hholds
  | eq => exact (hheads _ hatom).elim

/-! ## Finite progress of rejected blocker learning -/

/-- At one fixed node budget, production cannot reject blocked-open candidates
forever when each rejection blacklists at least one previously available fold.
This is the termination measure implemented by Rust's equality-free certified
producer: fold pairs range over the finite node universe and the forbidden set
grows strictly after every rejected candidate. -/
theorem no_infinite_fresh_fold_rejections
    [Fintype Node] [DecidableEq Node]
    (forbidden learned : Nat → Finset (Node × Node))
    (hstep : ∀ round,
      forbidden (round + 1) = forbidden round ∪ learned round)
    (hfresh : ∀ round, ∃ fold ∈ learned round, fold ∉ forbidden round) : False := by
  have hstrict : ∀ round, forbidden round ⊂ forbidden (round + 1) := by
    intro round
    refine Finset.ssubset_iff_subset_ne.mpr ⟨?_, ?_⟩
    · rw [hstep]
      exact Finset.subset_union_left
    · obtain ⟨fold, hlearned, hnew⟩ := hfresh round
      intro heq
      have hnext : fold ∈ forbidden (round + 1) := by
        rw [hstep]
        exact Finset.mem_union_right _ hlearned
      exact hnew (heq ▸ hnext)
  have hcard : ∀ round,
      (forbidden 0).card + round ≤ (forbidden round).card := by
    intro round
    induction round with
    | zero => simp
    | succ round ih =>
        have hlt := Finset.card_lt_card (hstrict round)
        omega
  have huniv := Finset.card_le_card
    (show forbidden (Fintype.card (Node × Node) + 1) ⊆ Finset.univ by
      exact Finset.subset_univ _)
  have hbound := hcard (Fintype.card (Node × Node) + 1)
  simp only [Finset.card_univ] at huniv
  omega

/-- One producer attempt at a fixed node budget either returns the checked
round result consumed by the outer doubling proof or rejects a finite set of
blocker folds. Rejection is an internal search refinement, never a verdict. -/
inductive FoldLearningOutcome (Node Result : Type) where
  | done (result : Result)
  | rejected (folds : Finset (Node × Node))

/-- Executable shape of one fixed-budget blocker retry loop. The next attempt
is a function of the current blacklist. A rejection must expose at least one
fold not already blacklisted; this is the local contract enforced by Rust
before it retries. -/
structure FreshFoldProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : Finset (Node × Node) → FoldLearningOutcome Node Result
  rejectionFresh : ∀ forbidden folds,
    attempt forbidden = .rejected folds →
      ∃ fold ∈ folds, fold ∉ forbidden

/-- Proof-carrying result of the Rust checker/blacklist branch at one fixed
budget. A rejected candidate stores its exact serialized fold set together
with the fact established by at least one successful `HashSet::insert`.
Consequently the fatal stale-fold branch is absent from this type. -/
inductive GuardedFoldAttempt (Node Result : Type)
    [DecidableEq Node] (forbidden : Finset (Node × Node)) : Type where
  | done (result : Result)
  | rejected (folds : Finset (Node × Node))
      (fresh : ∃ fold ∈ folds, fold ∉ forbidden)

def GuardedFoldAttempt.erase
    [DecidableEq Node]
    {forbidden : Finset (Node × Node)} :
    GuardedFoldAttempt Node Result forbidden → FoldLearningOutcome Node Result
  | .done result => .done result
  | .rejected folds _ => .rejected folds

/-- Rust-mirrored fixed-budget producer. Its attempt is indexed by the actual
blacklist supplied to the search, and rejection can only be constructed from
a candidate carrying a newly inserted blocker pair. -/
structure GuardedFoldProducer (Node Result : Type)
    [DecidableEq Node] where
  attempt : ∀ forbidden : Finset (Node × Node),
    GuardedFoldAttempt Node Result forbidden

def GuardedFoldProducer.toFreshFoldProducer
    [DecidableEq Node]
    (producer : GuardedFoldProducer Node Result) :
    FreshFoldProducer Node Result where
  attempt forbidden := (producer.attempt forbidden).erase
  rejectionFresh := by
    intro forbidden folds hrejected
    cases hattempt : producer.attempt forbidden with
    | done result => simp [GuardedFoldAttempt.erase, hattempt] at hrejected
    | rejected learned fresh =>
        simp [GuardedFoldAttempt.erase, hattempt] at hrejected
        subst learned
        exact fresh

theorem GuardedFoldProducer.rejected_has_fresh
    [DecidableEq Node]
    (producer : GuardedFoldProducer Node Result)
    {forbidden folds : Finset (Node × Node)}
    (hrejected : (producer.attempt forbidden).erase = .rejected folds) :
    ∃ fold ∈ folds, fold ∉ forbidden := by
  exact producer.toFreshFoldProducer.rejectionFresh forbidden folds hrejected

def FreshFoldProducer.forbidden
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) : Nat → Finset (Node × Node)
  | 0 => ∅
  | round + 1 =>
      let current := producer.forbidden round
      match producer.attempt current with
      | .done _ => current
      | .rejected folds => current ∪ folds

def FreshFoldProducer.run
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) (round : Nat) :
    FoldLearningOutcome Node Result :=
  producer.attempt (producer.forbidden round)

theorem FreshFoldProducer.rejected_step
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    {round : Nat} {folds : Finset (Node × Node)}
    (hrun : producer.run round = .rejected folds) :
    producer.forbidden (round + 1) = producer.forbidden round ∪ folds ∧
      ∃ fold ∈ folds, fold ∉ producer.forbidden round := by
  have hattempt : producer.attempt (producer.forbidden round) = .rejected folds := hrun
  constructor
  · simp only [FreshFoldProducer.forbidden]
    rw [hattempt]
  · exact producer.rejectionFresh _ _ hattempt

/-- A conforming producer cannot reject a candidate whose complete fold report
is already contained in the blacklist. This is the exact progress guard used
by the executable retry loop: rejection is permitted only when it teaches the
next attempt at least one new blocker pair. -/
theorem FreshFoldProducer.rejected_not_subset
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    {forbidden folds : Finset (Node × Node)}
    (hrejected : producer.attempt forbidden = .rejected folds) :
    ¬ folds ⊆ forbidden := by
  obtain ⟨fold, hfold, hfresh⟩ := producer.rejectionFresh forbidden folds hrejected
  exact fun hsubset => hfresh (hsubset hfold)

/-- In particular, the modeled production retry can never reach Rust's fatal
"fold-free candidate rejected" branch. Such an outcome carries no fresh fold
and therefore contradicts the producer contract. -/
theorem FreshFoldProducer.not_rejected_empty
    [DecidableEq Node]
    (producer : FreshFoldProducer Node Result)
    (forbidden : Finset (Node × Node)) :
    producer.attempt forbidden ≠ .rejected ∅ := by
  intro hrejected
  exact producer.rejected_not_subset hrejected (Finset.empty_subset _)

/-- The concrete retry layer terminates at every fixed node budget. This turns
the Rust producer's learned-fold loop into a total constructor of the checked
round outcome expected by the existing doubling theorem. -/
theorem fold_learning_eventually_done
    [Fintype Node] [DecidableEq Node]
    (run : Nat → FoldLearningOutcome Node Result)
    (forbidden : Nat → Finset (Node × Node))
    (hlearn : ∀ round folds, run round = .rejected folds →
      forbidden (round + 1) = forbidden round ∪ folds ∧
        ∃ fold ∈ folds, fold ∉ forbidden round) :
    ∃ round result, run round = .done result := by
  by_contra hdone
  have hrejected : ∀ round, ∃ folds, run round = .rejected folds := by
    intro round
    cases houtcome : run round with
    | done result =>
        exact False.elim (hdone ⟨round, result, houtcome⟩)
    | rejected folds => exact ⟨folds, rfl⟩
  choose learned hruns using hrejected
  apply no_infinite_fresh_fold_rejections forbidden learned
  · intro round
    exact (hlearn round (learned round) (hruns round)).1
  · intro round
    exact (hlearn round (learned round) (hruns round)).2

theorem FreshFoldProducer.eventually_done
    [Fintype Node] [DecidableEq Node]
    (producer : FreshFoldProducer Node Result) :
    ∃ round result, producer.run round = .done result := by
  exact fold_learning_eventually_done producer.run producer.forbidden
    (fun _ _ hrun => producer.rejected_step hrun)

/-- A blocker-aware runtime terminal and checked fold metadata supply every
regular-model invariant. In particular, saturation transfers by state equality
because the serializer no longer mutates the completion graph. -/
theorem FiniteRegularCertificate.check_of_blocked_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hcoverClosed : certificate.CoverClosed)
    (hcoverEdge : ∀ role source target,
      certificate.coverRelation role source target →
        certificate.state.edge role source target) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  exact certificate.check_of_producer_invariants hauthorized hguarded hheads
    hclash hwitness hcoverClosed hcoverEdge hsaturated

/-- Concrete producer theorem for the proved local residual fragment. Unlike
`check_of_blocked_runtime_terminal`, this theorem permits redirected cover
edges absent from the raw graph outside residual bodies. Local-fact invariance
and exact body-role cover containment pull every finite cover grounding back
to ordinary saturation. -/
theorem FiniteRegularCertificate.check_of_local_blocked_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hdirect : ∀ clause ∈ certificate.residual,
      certificate.state.DirectCoverForBody certificate.redirect
        certificate.coverRelation clause)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  have hcoverDischarges : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause := by
    intro clause hclause
    exact certificate.state.coverDischarges_of_singleDirectRoleBody
      certificate.redirect certificate.coverRelation clause
      (hshape clause hclause) hlocal (hdirect clause hclause)
      (hheads clause hclause)
      (hsaturated clause hclause)
  apply certificate.check_complete
  exact ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
    hcoverDischarges⟩

/-- Exact cover-aware producer boundary. A runtime search that has exhausted
residual obstructions in the redirected endpoint cover may publish a regular
model without imposing a syntactic restriction on residual bodies. This is
the semantic target for the cover-aware Rust terminal selector. -/
theorem FiniteRegularCertificate.check_of_cover_saturated_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hcoverClosed : certificate.CoverClosed)
    (hcoverSaturated : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  exact certificate.check_complete
    ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
      hcoverSaturated⟩

/-- General redirected-cover producer theorem. Redirecting both endpoints of
every cover edge back into the raw saturated graph removes the single-edge and
simple-role restrictions from residual bodies. -/
theorem FiniteRegularCertificate.check_of_redirect_cover_runtime_terminal
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hredirectCover : certificate.state.RedirectCoverFacts certificate.redirect
      certificate.coverRelation)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hclash : certificate.state.ClashFree := by
    rw [hstate]
    exact hterminal.clashFree
  have hwitness : certificate.state.RedirectWitnessComplete
      certificate.redirect := by
    rw [hstate]
    exact runtime.blockedRedirectWitnessComplete certificate.residual blocked
      fold certificate.redirect hterminal hwitnessRefines hredirectRefines
  have hsaturated : certificate.state.SaturatedFor certificate.residual := by
    rw [hstate]
    exact hterminal.saturatedFor
  have hcoverDischarges : ∀ clause ∈ certificate.residual,
      certificate.state.CoverDischarges certificate.coverRelation clause := by
    intro clause hclause
    exact certificate.state.coverDischarges_of_redirectCoverFacts
      certificate.redirect certificate.coverRelation clause hlocal
      hredirectCover (hheads clause hclause) (hsaturated clause hclause)
  apply certificate.check_complete
  exact ⟨hauthorized, hguarded, hheads, hclash, hwitness, hcoverClosed,
    hcoverDischarges⟩

/-- For residual clauses whose body roles are syntactically simple, the
serialized endpoint cover itself supplies the direct-body premise. This is the
premise-free cover bridge for the complete local blocking fragment: no
producer-specific assertion about each redirected cover edge remains. -/
theorem FiniteRegularCertificate.check_of_simple_local_blocked_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hwitnessRefines : runtime.BlockedWitnessRefines blocked fold)
    (hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hsimple : ∀ clause ∈ certificate.residual,
      clause.SimpleBodyRoles certificate.rules)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hlocal : certificate.state.RedirectLocalFacts certificate.redirect)
    (hgenerated : certificate.CoverGenerated)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  apply certificate.check_of_local_blocked_runtime_terminal runtime blocked fold
    hstate hterminal hwitnessRefines hredirectRefines hauthorized hguarded
    hshape hheads hlocal
  · intro clause hclause
    exact certificate.directCoverForBody_of_generated hgenerated clause
      (hsimple clause hclause)
  · exact hcoverClosed

/-- A saturated runtime terminal with no blocker folds is accepted using the
identity redirect. Fold-table totality forces every node to be unblocked, so
every existential obligation already has an ordinary runtime witness. This is
the checker-completeness argument for the final fold-free retry attempted by
the Rust producer. -/
theorem FiniteRegularCertificate.check_of_fold_free_runtime_terminal
    [DecidableEq (Fin variableCount)]
    (certificate : FiniteRegularCertificate
      nodeCount conceptCount roleCount variableCount)
    (runtime : State (Fin nodeCount) (Fin conceptCount) (Fin roleCount))
    (blocked : Fin nodeCount → Bool)
    (fold : Fin nodeCount → Fin nodeCount → Prop)
    (hstate : certificate.state = runtime)
    (hterminal : runtime.BlockedRuntimeTerminal certificate.residual blocked)
    (hfoldTotal : State.BlockedFoldTotal blocked fold)
    (hfoldFree : ∀ source blocker, ¬ fold source blocker)
    (hredirect : certificate.redirect = id)
    (hauthorized : ∀ rule ∈ certificate.roleClauses,
      rule.Authorized certificate.rules)
    (hguarded : ∀ clause ∈ certificate.residual, clause.GuardedBody)
    (hshape : ∀ clause ∈ certificate.residual, clause.SingleDirectRoleBody)
    (hheads : ∀ clause ∈ certificate.residual, ∀ atom ∈ clause.head,
      PathLiftableHead atom)
    (hdirect : ∀ clause ∈ certificate.residual,
      certificate.state.DirectCoverForBody certificate.redirect
        certificate.coverRelation clause)
    (hcoverClosed : certificate.CoverClosed) :
    certificate.check = true := by
  have hunblocked : ∀ source, blocked source = false := by
    intro source
    cases hblocked : blocked source with
    | false => rfl
    | true =>
        obtain ⟨blocker, hfold⟩ := hfoldTotal source hblocked
        exact (hfoldFree source blocker hfold).elim
  have hwitnessRefines : runtime.BlockedWitnessRefines blocked fold := by
    intro source role filler hobligation hblocked
    simp [hunblocked source] at hblocked
  have hredirectRefines : State.BlockedRedirectRefines blocked fold
      certificate.redirect := by
    constructor
    · intro source _
      simp [hredirect]
    · intro source blocker hfold
      exact (hfoldFree source blocker hfold).elim
  have hlocal : certificate.state.RedirectLocalFacts certificate.redirect := by
    simp [State.RedirectLocalFacts, hredirect]
  exact certificate.check_of_local_blocked_runtime_terminal runtime blocked fold
    hstate hterminal hwitnessRefines hredirectRefines hauthorized hguarded hshape
    hheads hlocal hdirect hcoverClosed

#print axioms FiniteRegularCertificate.check_of_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_local_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_cover_saturated_runtime_terminal
#print axioms State.coverDischarges_of_redirectCoverFacts
#print axioms FiniteRegularCertificate.check_of_redirect_cover_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_simple_local_blocked_runtime_terminal
#print axioms FiniteRegularCertificate.check_of_fold_free_runtime_terminal
#print axioms no_infinite_fresh_fold_rejections
#print axioms fold_learning_eventually_done
#print axioms FreshFoldProducer.rejected_step
#print axioms FreshFoldProducer.rejected_not_subset
#print axioms FreshFoldProducer.not_rejected_empty
#print axioms FreshFoldProducer.eventually_done
#print axioms GuardedFoldProducer.rejected_has_fresh

end ContextCalculus.Hypertableau
