-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `disj` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_disj : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩]

def cert_disj_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 2 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0))), FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 0 1 (FLit.P (FPred.concept 2 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 4 2 (FLit.P (FPred.concept 3 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 3 5 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem disj_0_A_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_disj, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 4 a0 :=
  certifies_subsumptionT O_disj 1 4 cert_disj_0 (by decide) M hO a0 hA

def cert_disj_1 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 2 (FTerm.var (0))))) ]
theorem disj_1_B_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_disj, valid M p) (a0 : D) (hA : M.conc 2 a0) : M.conc 4 a0 :=
  certifies_subsumptionT O_disj 2 4 cert_disj_1 (by decide) M hO a0 hA

def cert_disj_2 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 2 []),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 3 (FTerm.var (0))))) ]
theorem disj_2_C_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_disj, valid M p) (a0 : D) (hA : M.conc 3 a0) : M.conc 4 a0 :=
  certifies_subsumptionT O_disj 3 4 cert_disj_2 (by decide) M hO a0 hA

