-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `disjoint` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_disjoint : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 3 (FTerm.var (0)))], []⟩]

def cert_disjoint_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem disjoint_0_A_sub_C {D : Type} (M : TModel D) (hO : ∀ p ∈ O_disjoint, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_disjoint 1 3 cert_disjoint_0 (by decide) M hO a0 hA

def cert_disjoint_1 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 3 (FTerm.var (0)))], []⟩, .prem 2 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0))), FLit.P (FPred.concept 2 (FTerm.var (0)))], []⟩, .res 1 2 (FLit.P (FPred.concept 3 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], []⟩, .res 0 4 (FLit.P (FPred.concept 2 (FTerm.var (0))))),
    (⟨[], []⟩, .res 3 5 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem disjoint_1_A_unsat {D : Type} (M : TModel D) (hO : ∀ p ∈ O_disjoint, valid M p) (a0 : D) : ¬ M.conc 1 a0 :=
  certifies_unsatT O_disjoint 1 cert_disjoint_1 (by decide) M hO a0

