-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `exists` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_exists : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 3 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩]

def cert_exists_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 1 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .res 2 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .res 2 1 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 2 [((0), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0))))]⟩, .res 4 5 (FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 3 [((-2), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 6 7 (FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 3 8 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))))) ]
theorem exists_0_A_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_exists, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 4 a0 :=
  certifies_subsumptionT O_exists 1 4 cert_exists_0 (by decide) M hO a0 hA

def cert_exists_1 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 2 []),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 2 (FTerm.var (0))))) ]
theorem exists_1_B_sub_C {D : Type} (M : TModel D) (hO : ∀ p ∈ O_exists, valid M p) (a0 : D) (hA : M.conc 2 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_exists 2 3 cert_exists_1 (by decide) M hO a0 hA

