-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `forall_intro` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_forall_intro : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 2 (FTerm.var (-2)))]⟩, ⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 6 (FTerm.var (0))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 4 (FTerm.var (-2)))]⟩, ⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0))), FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 6 (FTerm.var (0))), FLit.P (FPred.concept 7 (FTerm.var (0)))], []⟩, ⟨[FLit.P (FPred.concept 7 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 7 (FTerm.var (0)))], [FLit.P (FPred.concept 8 (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0))), FLit.P (FPred.concept 8 (FTerm.var (0)))], []⟩, ⟨[FLit.P (FPred.concept 9 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 6 (FTerm.var (0)))], [FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩]

def cert_forall_intro_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0))), FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .prem 6 []),
    (⟨[FLit.P (FPred.concept 7 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 8 []),
    (⟨[FLit.P (FPred.concept 7 (FTerm.var (0)))], [FLit.P (FPred.concept 8 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 9 []),
    (⟨[FLit.P (FPred.concept 6 (FTerm.var (0)))], [FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .prem 12 []),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .res 5 0 (FLit.P (FPred.concept 3 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 7 (FTerm.var (0))), FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 1 4 (FLit.P (FPred.concept 6 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 9 (FTerm.var (0))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .res 7 2 (FLit.P (FPred.concept 7 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 8 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 7 3 (FLit.P (FPred.concept 7 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 0 [((-2), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .res 6 10 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 8 11 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 4 [((0), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.concept 4 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 8 (FTerm.app 1 (FTerm.var (0))))], []⟩, .prem 10 [((0), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 12 13 (FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 4 (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 9 14 (FLit.P (FPred.concept 8 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[], [FLit.P (FPred.concept 9 (FTerm.var (0)))]⟩, .res 15 16 (FLit.P (FPred.concept 4 (FTerm.app 1 (FTerm.var (0)))))) ]
theorem forall_intro_0_A_sub_B {D : Type} (M : TModel D) (hO : ∀ p ∈ O_forall_intro, valid M p) (a0 : D) (hA : M.conc 3 a0) : M.conc 9 a0 :=
  certifies_subsumptionT O_forall_intro 3 9 cert_forall_intro_0 (by decide) M hO a0 hA

