-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `hierarchy` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_hierarchy : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (0))), FLit.P (FPred.concept 5 (FTerm.var (0)))], []⟩]

def cert_hierarchy_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .prem 0 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem hierarchy_0_Father_sub_Male {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 2 a0 :=
  certifies_subsumptionT O_hierarchy 1 2 cert_hierarchy_0 (by decide) M hO a0 hA

def cert_hierarchy_1 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .prem 7 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .res 0 1 (FLit.P (FPred.concept 3 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .res 2 3 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem hierarchy_1_Father_sub_Narcissist {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 7 a0 :=
  certifies_subsumptionT O_hierarchy 1 7 cert_hierarchy_1 (by decide) M hO a0 hA

def cert_hierarchy_2 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 1 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem hierarchy_2_Father_sub_Parent {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_hierarchy 1 3 cert_hierarchy_2 (by decide) M hO a0 hA

def cert_hierarchy_3 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .prem 5 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 0 1 (FLit.P (FPred.concept 2 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 2 3 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem hierarchy_3_Father_sub_Person {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 6 a0 :=
  certifies_subsumptionT O_hierarchy 1 6 cert_hierarchy_3 (by decide) M hO a0 hA

def cert_hierarchy_4 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .prem 6 []),
    (⟨[], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 5 (FTerm.var (0))))) ]
theorem hierarchy_4_Female_sub_Person {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 5 a0) : M.conc 6 a0 :=
  certifies_subsumptionT O_hierarchy 5 6 cert_hierarchy_4 (by decide) M hO a0 hA

def cert_hierarchy_5 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 2 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .prem 5 []),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 2 (FTerm.var (0))))) ]
theorem hierarchy_5_Male_sub_Person {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 2 a0) : M.conc 6 a0 :=
  certifies_subsumptionT O_hierarchy 2 6 cert_hierarchy_5 (by decide) M hO a0 hA

def cert_hierarchy_6 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, .prem 2 []),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 4 (FTerm.var (0))))) ]
theorem hierarchy_6_Mother_sub_Female {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 4 a0) : M.conc 5 a0 :=
  certifies_subsumptionT O_hierarchy 4 5 cert_hierarchy_6 (by decide) M hO a0 hA

def cert_hierarchy_7 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 3 []),
    (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .prem 7 []),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .res 0 1 (FLit.P (FPred.concept 3 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .res 2 3 (FLit.P (FPred.concept 4 (FTerm.var (0))))) ]
theorem hierarchy_7_Mother_sub_Narcissist {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 4 a0) : M.conc 7 a0 :=
  certifies_subsumptionT O_hierarchy 4 7 cert_hierarchy_7 (by decide) M hO a0 hA

def cert_hierarchy_8 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 3 []),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 4 (FTerm.var (0))))) ]
theorem hierarchy_8_Mother_sub_Parent {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 4 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_hierarchy 4 3 cert_hierarchy_8 (by decide) M hO a0 hA

def cert_hierarchy_9 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, .prem 2 []),
    (⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .prem 6 []),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 0 1 (FLit.P (FPred.concept 5 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 2 3 (FLit.P (FPred.concept 4 (FTerm.var (0))))) ]
theorem hierarchy_9_Mother_sub_Person {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 4 a0) : M.conc 6 a0 :=
  certifies_subsumptionT O_hierarchy 4 6 cert_hierarchy_9 (by decide) M hO a0 hA

def cert_hierarchy_10 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .prem 7 []),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 3 (FTerm.var (0))))) ]
theorem hierarchy_10_Parent_sub_Narcissist {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 3 a0) : M.conc 7 a0 :=
  certifies_subsumptionT O_hierarchy 3 7 cert_hierarchy_10 (by decide) M hO a0 hA

def cert_hierarchy_11 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 3 (FTerm.var (0)))], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .prem 4 []),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 3 (FTerm.var (0))))) ]
theorem hierarchy_11_Parent_sub_Person {D : Type} (M : TModel D) (hO : ∀ p ∈ O_hierarchy, valid M p) (a0 : D) (hA : M.conc 3 a0) : M.conc 6 a0 :=
  certifies_subsumptionT O_hierarchy 3 6 cert_hierarchy_11 (by decide) M hO a0 hA

