-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `numrestr` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_numrestr : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0))), FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))], []⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (-3))), FLit.P (FPred.concept 2 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-3))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.eq (FTerm.var (-2)) (FTerm.var (-3))]⟩]

def cert_numrestr_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 1 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 2 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 3 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0))), FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))], []⟩, .prem 4 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .res 5 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .res 5 1 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .res 5 2 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 2 (FTerm.var (0))))]⟩, .res 5 3 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 2 (FTerm.app 2 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))]⟩, .prem 5 [((-3), (FTerm.app 2 (FTerm.var (0)))), ((-2), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))]⟩, .res 9 10 (FLit.P (FPred.concept 2 (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))]⟩, .res 7 11 (FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))]⟩, .res 8 12 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[], [FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))]⟩, .res 6 13 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0)))], []⟩, .res 5 4 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], []⟩, .res 14 15 (FLit.eq (FTerm.app 1 (FTerm.var (0))) (FTerm.app 2 (FTerm.var (0))))) ]
theorem numrestr_0_A_unsat {D : Type} (M : TModel D) (hO : ∀ p ∈ O_numrestr, valid M p) (a0 : D) : ¬ M.conc 1 a0 :=
  certifies_unsatT O_numrestr 1 cert_numrestr_0 (by decide) M hO a0

