-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `paramod` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_paramod : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-3))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.eq (FTerm.var (-2)) (FTerm.var (-3))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (-4))), FLit.P (FPred.concept 3 (FTerm.var (-4))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-4)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩]

def cert_paramod_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 0 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .prem 1 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 2 []),
    (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 3 []),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, .res 4 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, .res 4 1 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .res 4 2 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.app 2 (FTerm.var (0))))]⟩, .res 4 3 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.eq (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.var (0)))]⟩, .prem 4 [((-3), (FTerm.app 1 (FTerm.var (0)))), ((-2), (FTerm.app 2 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.eq (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.var (0)))]⟩, .res 7 9 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[], [FLit.eq (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.var (0)))]⟩, .res 5 10 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0))))]⟩, .para 11 8 (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.var (0))) (FLit.P (FPred.concept 3 (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 5 [((-4), (FTerm.app 1 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0)))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 6 13 (FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 12 14 (FLit.P (FPred.concept 3 (FTerm.app 1 (FTerm.var (0)))))),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 5 15 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0)))))) ]
theorem paramod_0_A_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_paramod, valid M p) (a0 : D) (hA : M.conc 1 a0) : M.conc 4 a0 :=
  certifies_subsumptionT O_paramod 1 4 cert_paramod_0 (by decide) M hO a0 hA

