-- AUTO-GENERATED by certgen_term.py: kernel-checked validation of the
-- Rust reasoner's verdicts on `trans_test` against ContextCalculus.CheckerTerm.
import ContextCalculus.CheckerTerm
open ContextCalculus ContextCalculus.CheckerTerm
set_option maxRecDepth 8000

def O_trans_test : List FCL := [⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 5 (FTerm.app 2 (FTerm.var (0))))]⟩, ⟨[FLit.P (FPred.concept 5 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 6 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.role 1 (FTerm.var (-2)) (FTerm.var (-3))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-3)))]⟩, ⟨[FLit.P (FPred.concept 2 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 7 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 7 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 7 (FTerm.var (0)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 5 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 8 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 8 (FTerm.var (-2))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.var (-2)))], [FLit.P (FPred.concept 8 (FTerm.var (0)))]⟩, ⟨[FLit.P (FPred.concept 8 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩]

def cert_trans_test_0 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 3 []),
    (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 4 []),
    (⟨[FLit.P (FPred.concept 4 (FTerm.var (0)))], [FLit.P (FPred.concept 5 (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 5 []),
    (⟨[FLit.P (FPred.concept 6 (FTerm.var (0)))], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .prem 7 []),
    (⟨[], [FLit.P (FPred.concept 6 (FTerm.var (0)))]⟩, .core),
    (⟨[], [FLit.P (FPred.concept 4 (FTerm.var (0)))]⟩, .res 4 3 (FLit.P (FPred.concept 6 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))]⟩, .res 5 1 (FLit.P (FPred.concept 4 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 5 (FTerm.app 2 (FTerm.var (0))))]⟩, .res 5 2 (FLit.P (FPred.concept 4 (FTerm.var (0))))),
    (⟨[FLit.P (FPred.concept 5 (FTerm.app 2 (FTerm.var (0))))], [FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0))))]⟩, .prem 8 [((0), (FTerm.app 2 (FTerm.var (0))))]),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0))))]⟩, .res 7 8 (FLit.P (FPred.concept 5 (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0))))], [FLit.P (FPred.role 1 (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .prem 0 [((0), (FTerm.app 2 (FTerm.var (0))))]),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .res 9 10 (FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0))))], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .prem 1 [((0), (FTerm.app 2 (FTerm.var (0))))]),
    (⟨[], [FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .res 9 12 (FLit.P (FPred.concept 1 (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.role 1 (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .prem 9 [((-3), (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))), ((-2), (FTerm.app 2 (FTerm.var (0))))]),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0))))], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .res 11 14 (FLit.P (FPred.role 1 (FTerm.app 2 (FTerm.var (0))) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))))),
    (⟨[], [FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]⟩, .res 6 15 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 2 (FTerm.var (0)))))),
    (⟨[FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))), FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .prem 2 [((-2), (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))]),
    (⟨[FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0)))))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .res 13 17 (FLit.P (FPred.concept 2 (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))))),
    (⟨[], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .res 16 18 (FLit.P (FPred.role 1 (FTerm.var (0)) (FTerm.app 1 (FTerm.app 2 (FTerm.var (0))))))),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 19 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))) ]
theorem trans_test_0_A_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_trans_test, valid M p) (a0 : D) (hA : M.conc 6 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_trans_test 6 3 cert_trans_test_0 (by decide) M hO a0 hA

def cert_trans_test_1 : List (FCL × JustifT) :=
  [ (⟨[FLit.P (FPred.concept 1 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .prem 3 []),
    (⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 1 (FTerm.var (0)))]⟩, .prem 8 []),
    (⟨[], [FLit.P (FPred.concept 5 (FTerm.var (0)))]⟩, .core),
    (⟨[FLit.P (FPred.concept 5 (FTerm.var (0)))], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 1 0 (FLit.P (FPred.concept 1 (FTerm.var (0))))),
    (⟨[], [FLit.P (FPred.concept 3 (FTerm.var (0)))]⟩, .res 2 3 (FLit.P (FPred.concept 5 (FTerm.var (0))))) ]
theorem trans_test_1_B_sub_D {D : Type} (M : TModel D) (hO : ∀ p ∈ O_trans_test, valid M p) (a0 : D) (hA : M.conc 5 a0) : M.conc 3 a0 :=
  certifies_subsumptionT O_trans_test 5 3 cert_trans_test_1 (by decide) M hO a0 hA

