/- Kernel-checked validation of the actual Rust reasoner's verdicts.
   Auto-generated by `engine/py/certgen_term.py` from real engine
   runs; every theorem is proved by the Lean-verified term-algebra checker
   `ContextCalculus.CheckerTerm` via `decide` (axioms: propext, Quot.sound).
   The term algebra represents nested successors `f(g(x))`, so transitive-role
   and successor-chain subsumptions are certified by kernel, not just empirically.

   Hand-authored normalised inputs (one per rule class):           -/
import Validation.Disj         -- disjunctive subsumption (Hyper)
import Validation.Disjoint     -- disjointness clash (⊥)
import Validation.Hierarchy    -- class hierarchy (resolution)
import Validation.Exists       -- ∃R / value restriction (Succ)
import Validation.Numrestr     -- number restrictions (Eq/Factor)
import Validation.Paramod      -- paramodulation into a literal (superposition)
import Validation.Disjsucc     -- disjunction x successor together (complete engine)
/- Sourced from real `.ofn` ontologies via the front-end (`frontend.py`):       -/
import Validation.Transtest    -- transitive role incl. nested A ⊑ D (trans_test.ofn)
import Validation.Kinship      -- 21 subsumptions of kinship.ofn (incl. a nominal)
import Validation.ForallIntro  -- ∀-introduction: A ⊑ B for B ≡ ∀r.(C⊔D) (forall_intro.ofn)
